export type ColorOption = {
  name: string;
  hex: string;
  image: string;
};

export type Product = {
  slug: string;
  name: string;
  price: number;
  originalPrice?: number;
  image: string;
  images?: string[];
  seller: string;
  sellerTier: "Pro" | "Standard";
  badge?: "NEW" | "BESTSELLER" | "SALE";
  colors: ColorOption[];
  gender: "mens" | "womens" | "unisex";
  category: "shoes" | "apparel" | "accessories";
  material?: string;
  sizes: number[];
  rating: number;
  reviews: number;
  description?: string;
  features?: string[];
  inStock: boolean;
  collections: string[];
};

export const products: Product[] = [
  {
    slug: "cloud-runner",
    name: "Cloud Runner",
    price: 479,
    image: "/images/products/product-1.jpg",
    images: ["/images/products/product-1.jpg", "/images/products/product-9.jpg", "/images/products/product-3.jpg"],
    seller: "UrbanEdge",
    sellerTier: "Pro",
    badge: "BESTSELLER",
    colors: [{ name: "Jet Black", hex: "#1a1a1a", image: "/images/products/product-1.jpg" }, { name: "Stone White", hex: "#f0ede6", image: "/images/products/product-9.jpg" }, { name: "Olive", hex: "#5c6b4f", image: "/images/products/product-3.jpg" }],
    gender: "mens",
    category: "shoes",
    material: "mesh",
    sizes: [7, 8, 9, 10, 11, 12, 13],
    rating: 4.7,
    reviews: 312,
    description: "A lightweight everyday runner with a breathable knit upper and cushioned sole. Built for comfort from morning to night.",
    inStock: true,
    collections: ["mens", "new-arrivals", "best-sellers"],
  },
  {
    slug: "trail-pacer",
    name: "Trail Pacer",
    price: 559,
    image: "/images/products/product-3.jpg",
    images: ["/images/products/product-3.jpg", "/images/products/product-7.jpg"],
    seller: "UrbanEdge",
    sellerTier: "Pro",
    badge: "NEW",
    colors: [{ name: "Forest Green", hex: "#3d5a3d", image: "/images/products/product-3.jpg" }, { name: "Charcoal", hex: "#333333", image: "/images/products/product-7.jpg" }],
    gender: "mens",
    category: "shoes",
    material: "wool",
    sizes: [7, 8, 9, 10, 11, 12, 13],
    rating: 4.5,
    reviews: 178,
    description: "Rugged enough for the trail, comfortable enough for all day. Grippy outsole meets cloud-like cushioning.",
    inStock: true,
    collections: ["mens", "new-arrivals"],
  },
  {
    slug: "dash-sport",
    name: "Dash Sport",
    price: 579,
    image: "/images/products/product-6.jpg",
    images: ["/images/products/product-6.jpg", "/images/products/product-1.jpg"],
    seller: "UrbanEdge",
    sellerTier: "Pro",
    badge: "NEW",
    colors: [{ name: "Storm Blue", hex: "#4a6fa5", image: "/images/products/product-6.jpg" }, { name: "Black", hex: "#1a1a1a", image: "/images/products/product-1.jpg" }],
    gender: "mens",
    category: "shoes",
    material: "mesh",
    sizes: [7, 8, 9, 10, 11, 12, 13],
    rating: 4.3,
    reviews: 156,
    description: "Engineered for performance. Responsive cushioning and a breathable upper for your best run yet.",
    inStock: true,
    collections: ["mens", "new-arrivals"],
  },
  {
    slug: "summit-hiker",
    name: "Summit Hiker",
    price: 639,
    image: "/images/products/product-14.jpg",
    images: ["/images/products/product-14.jpg", "/images/products/product-7.jpg"],
    seller: "UrbanEdge",
    sellerTier: "Pro",
    colors: [{ name: "Earth Brown", hex: "#6b5b4a", image: "/images/products/product-14.jpg" }, { name: "Charcoal", hex: "#333333", image: "/images/products/product-7.jpg" }],
    gender: "mens",
    category: "shoes",
    material: "wool",
    sizes: [7, 8, 9, 10, 11, 12, 13],
    rating: 4.8,
    reviews: 98,
    description: "Built for the outdoors but comfortable enough for everyday. Waterproof and warm.",
    inStock: true,
    collections: ["mens"],
  },
  {
    slug: "pullover-hoodie-mens",
    name: "Pullover Hoodie",
    price: 389,
    image: "/images/products/product-20.jpg",
    images: ["/images/products/product-20.jpg", "/images/products/product-21.jpg"],
    seller: "UrbanEdge",
    sellerTier: "Pro",
    colors: [{ name: "Charcoal", hex: "#333333", image: "/images/products/product-20.jpg" }, { name: "Navy", hex: "#2a3a5c", image: "/images/products/product-21.jpg" }],
    gender: "mens",
    category: "apparel",
    material: "wool",
    sizes: [1, 2, 3, 4],
    rating: 4.8,
    reviews: 112,
    description: "A cozy merino wool hoodie that regulates temperature naturally. Warm without the bulk.",
    inStock: true,
    collections: ["mens", "apparel"],
  },
  {
    slug: "jogger-pant-mens",
    name: "Jogger Pant",
    price: 349,
    image: "/images/products/product-24.jpg",
    images: ["/images/products/product-24.jpg", "/images/products/product-25.jpg"],
    seller: "UrbanEdge",
    sellerTier: "Pro",
    colors: [{ name: "Black", hex: "#1a1a1a", image: "/images/products/product-24.jpg" }, { name: "Charcoal", hex: "#333333", image: "/images/products/product-25.jpg" }],
    gender: "mens",
    category: "apparel",
    material: "knit",
    sizes: [1, 2, 3, 4],
    rating: 4.5,
    reviews: 95,
    description: "Tapered joggers with a soft knit fabric that moves with you. Refined enough for the coffee shop.",
    inStock: true,
    collections: ["mens", "apparel"],
  },
  {
    slug: "lightweight-jacket-mens",
    name: "Lightweight Jacket",
    price: 509,
    image: "/images/products/product-22.jpg",
    images: ["/images/products/product-22.jpg", "/images/products/product-23.jpg"],
    seller: "UrbanEdge",
    sellerTier: "Pro",
    badge: "NEW",
    colors: [{ name: "Black", hex: "#1a1a1a", image: "/images/products/product-22.jpg" }, { name: "Olive", hex: "#5c6b4f", image: "/images/products/product-23.jpg" }],
    gender: "mens",
    category: "apparel",
    material: "mesh",
    sizes: [1, 2, 3, 4],
    rating: 4.4,
    reviews: 67,
    description: "A windproof jacket that packs into its own pocket. Light enough to carry everywhere.",
    inStock: true,
    collections: ["mens", "apparel", "new-arrivals"],
  },
  {
    slug: "street-runner-x",
    name: "Street Runner X",
    price: 499,
    image: "/images/products/product-1.jpg",
    images: ["/images/products/product-1.jpg", "/images/products/product-9.jpg", "/images/products/product-8.jpg"],
    seller: "UrbanEdge",
    sellerTier: "Pro",
    badge: "NEW",
    colors: [{ name: "Triple Black", hex: "#0a0a0a", image: "/images/products/product-1.jpg" }, { name: "Off White", hex: "#f5f0eb", image: "/images/products/product-9.jpg" }, { name: "Storm Grey", hex: "#6b7280", image: "/images/products/product-8.jpg" }],
    gender: "mens",
    category: "shoes",
    material: "mesh",
    sizes: [7, 8, 9, 10, 11, 12, 13],
    rating: 4.6,
    reviews: 84,
    description: "Street-level aesthetics meet next-gen cushioning. The X takes the Cloud Runner silhouette and drops it into the urban landscape with a heavier outsole and bolder colorways.",
    inStock: true,
    collections: ["mens", "new-arrivals"],
  },
  {
    slug: "stealth-hoodie",
    name: "Stealth Hoodie",
    price: 429,
    image: "/images/products/product-20.jpg",
    images: ["/images/products/product-20.jpg", "/images/products/product-21.jpg"],
    seller: "UrbanEdge",
    sellerTier: "Pro",
    badge: "NEW",
    colors: [{ name: "Washed Black", hex: "#2a2a2a", image: "/images/products/product-20.jpg" }, { name: "Olive", hex: "#5c6b4f", image: "/images/products/product-21.jpg" }, { name: "Charcoal", hex: "#333333", image: "/images/products/product-20.jpg" }],
    gender: "mens",
    category: "apparel",
    material: "knit",
    sizes: [1, 2, 3, 4],
    rating: 4.5,
    reviews: 63,
    description: "Heavyweight oversized hoodie with dropped shoulders and a boxy cut. The kind of piece that anchors your whole fit. Double-layered hood, hidden side zip pockets, ribbed cuffs that actually stay put.",
    inStock: true,
    collections: ["mens", "apparel", "new-arrivals"],
  },
  {
    slug: "cargo-jogger",
    name: "Cargo Jogger",
    price: 399,
    image: "/images/products/product-24.jpg",
    images: ["/images/products/product-24.jpg", "/images/products/product-25.jpg"],
    seller: "UrbanEdge",
    sellerTier: "Pro",
    colors: [{ name: "Black", hex: "#1a1a1a", image: "/images/products/product-24.jpg" }, { name: "Olive", hex: "#5c6b4f", image: "/images/products/product-25.jpg" }],
    gender: "mens",
    category: "apparel",
    material: "knit",
    sizes: [1, 2, 3, 4],
    rating: 4.4,
    reviews: 47,
    description: "Tapered cargo joggers with oversized utility pockets and a drawcord waist. Streetwear utility meets everyday comfort in a heavyweight cotton-poly blend.",
    inStock: true,
    collections: ["mens", "apparel"],
  },
  {
    slug: "nightfall-runner",
    name: "Nightfall Runner",
    price: 529,
    image: "/images/products/product-1.jpg",
    images: ["/images/products/product-1.jpg", "/images/products/product-6.jpg"],
    seller: "UrbanEdge",
    sellerTier: "Pro",
    colors: [{ name: "Shadow Black", hex: "#111111", image: "/images/products/product-1.jpg" }, { name: "Neon Accent", hex: "#c4ff00", image: "/images/products/product-6.jpg" }],
    gender: "mens",
    category: "shoes",
    material: "mesh",
    sizes: [7, 8, 9, 10, 11, 12, 13],
    rating: 4.3,
    reviews: 39,
    description: "Full reflective detailing on a blacked-out runner. Visibility meets attitude for after-dark sessions and early mornings.",
    inStock: true,
    collections: ["mens"],
  },
  {
    slug: "utility-jacket",
    name: "Utility Jacket",
    price: 599,
    image: "/images/products/product-22.jpg",
    images: ["/images/products/product-22.jpg", "/images/products/product-23.jpg"],
    seller: "UrbanEdge",
    sellerTier: "Pro",
    colors: [{ name: "Black", hex: "#1a1a1a", image: "/images/products/product-22.jpg" }, { name: "Army Green", hex: "#4a5a3a", image: "/images/products/product-23.jpg" }],
    gender: "mens",
    category: "apparel",
    material: "mesh",
    sizes: [1, 2, 3, 4],
    rating: 4.7,
    reviews: 28,
    description: "Military-inspired utility jacket with a modern streetwear cut. Multiple pockets, adjustable waist cinch, and a water-resistant shell that handles city weather.",
    inStock: true,
    collections: ["mens", "apparel"],
  },
  {
    slug: "urban-slide",
    name: "Urban Slide",
    price: 219,
    image: "/images/products/product-16.jpg",
    images: ["/images/products/product-16.jpg", "/images/products/product-8.jpg"],
    seller: "UrbanEdge",
    sellerTier: "Pro",
    colors: [{ name: "Black", hex: "#1a1a1a", image: "/images/products/product-16.jpg" }, { name: "Olive", hex: "#5c6b4f", image: "/images/products/product-8.jpg" }],
    gender: "mens",
    category: "shoes",
    material: "tree-fiber",
    sizes: [7, 8, 9, 10, 11, 12],
    rating: 4.1,
    reviews: 52,
    description: "Chunky-sole slide for post-gym or lazy weekends. Contoured footbed with extra arch support. The kind of slide you actually want to be seen in.",
    inStock: true,
    collections: ["mens"],
  },
  {
    slug: "block-tee",
    name: "Block Tee",
    price: 199,
    image: "/images/products/product-17.jpg",
    images: ["/images/products/product-17.jpg", "/images/products/product-18.jpg", "/images/products/product-19.jpg"],
    seller: "UrbanEdge",
    sellerTier: "Pro",
    colors: [{ name: "Black", hex: "#1a1a1a", image: "/images/products/product-17.jpg" }, { name: "White", hex: "#f0ede6", image: "/images/products/product-18.jpg" }, { name: "Grey", hex: "#8a8a8a", image: "/images/products/product-19.jpg" }],
    gender: "mens",
    category: "apparel",
    material: "tree-fiber",
    sizes: [1, 2, 3, 4],
    rating: 4.3,
    reviews: 71,
    description: "Heavyweight boxy tee with a dropped shoulder. Clean block fit, no logos, no noise - just good fabric and a silhouette that works with everything.",
    inStock: true,
    collections: ["mens", "apparel"],
  },
  {
    slug: "drift-trainer",
    name: "Drift Trainer",
    price: 459,
    image: "/images/products/product-1.jpg",
    images: ["/images/products/product-1.jpg", "/images/products/product-8.jpg", "/images/products/product-6.jpg"],
    seller: "UrbanEdge",
    sellerTier: "Pro",
    colors: [{ name: "Black", hex: "#1a1a1a", image: "/images/products/product-1.jpg" }, { name: "Stone", hex: "#c4b59a", image: "/images/products/product-8.jpg" }, { name: "Navy", hex: "#2a3a5c", image: "/images/products/product-6.jpg" }],
    gender: "mens",
    category: "shoes",
    material: "mesh",
    sizes: [7, 8, 9, 10, 11, 12, 13],
    rating: 4.6,
    reviews: 123,
    description: "The do-everything trainer. From the gym floor to the bar stool - responsive cushioning wrapped in a clean, minimal upper that doesn't try too hard.",
    inStock: true,
    collections: ["mens", "best-sellers"],
  },
  {
    slug: "edge-runner-pro",
    name: "Edge Runner Pro",
    price: 549,
    image: "/images/products/product-8.jpg",
    images: ["/images/products/product-8.jpg", "/images/products/product-1.jpg"],
    seller: "UrbanEdge",
    sellerTier: "Pro",
    badge: "NEW",
    colors: [{ name: "Cement", hex: "#8a8a8a", image: "/images/products/product-8.jpg" }, { name: "Black", hex: "#1a1a1a", image: "/images/products/product-1.jpg" }],
    gender: "mens",
    category: "shoes",
    material: "knit",
    sizes: [7, 8, 9, 10, 11, 12, 13],
    rating: 4.5,
    reviews: 31,
    description: "Full-knit runner with a sock-like collar and a stacked midsole. Built for the streets, not the track. Premium materials, premium comfort, zero compromise.",
    inStock: true,
    collections: ["mens", "new-arrivals"],
  },
  {
    slug: "windbreaker-pullover",
    name: "Windbreaker Pullover",
    price: 449,
    image: "/images/products/product-22.jpg",
    images: ["/images/products/product-22.jpg", "/images/products/product-23.jpg"],
    seller: "UrbanEdge",
    sellerTier: "Pro",
    colors: [{ name: "Black", hex: "#1a1a1a", image: "/images/products/product-22.jpg" }, { name: "Navy", hex: "#2a3a5c", image: "/images/products/product-23.jpg" }],
    gender: "mens",
    category: "apparel",
    material: "mesh",
    sizes: [1, 2, 3, 4],
    rating: 4.2,
    reviews: 22,
    description: "Half-zip windbreaker with a kangaroo pocket and mesh lining. Packs flat, blocks wind, looks good doing both.",
    inStock: true,
    collections: ["mens", "apparel"],
  },
  {
    slug: "grip-hiker-low",
    name: "Grip Hiker Low",
    price: 489,
    image: "/images/products/product-14.jpg",
    images: ["/images/products/product-14.jpg", "/images/products/product-7.jpg"],
    seller: "UrbanEdge",
    sellerTier: "Pro",
    colors: [{ name: "Earth", hex: "#6b5b4a", image: "/images/products/product-14.jpg" }, { name: "Black", hex: "#1a1a1a", image: "/images/products/product-7.jpg" }],
    gender: "mens",
    category: "shoes",
    material: "leather",
    sizes: [7, 8, 9, 10, 11, 12, 13],
    rating: 4.4,
    reviews: 18,
    description: "Low-cut hiker with a leather upper and aggressive lug sole. Trail-ready with a profile clean enough for the city.",
    inStock: true,
    collections: ["mens"],
  },
  {
    slug: "raw-tee",
    name: "Raw Tee",
    price: 249,
    image: "/images/products/product-17.jpg",
    images: ["/images/products/product-17.jpg", "/images/products/product-18.jpg"],
    seller: "UrbanEdge",
    sellerTier: "Pro",
    colors: [{ name: "Washed Black", hex: "#2a2a2a", image: "/images/products/product-17.jpg" }, { name: "Sand", hex: "#c4b59a", image: "/images/products/product-18.jpg" }],
    gender: "mens",
    category: "apparel",
    material: "tree-fiber",
    sizes: [1, 2, 3, 4],
    rating: 4.2,
    reviews: 34,
    description: "Raw-edge tee with a relaxed, slightly cropped fit. Enzyme-washed for a broken-in feel from day one.",
    inStock: true,
    collections: ["mens", "apparel"],
  },
  {
    slug: "shadow-trainer",
    name: "Shadow Trainer",
    price: 439,
    image: "/images/products/product-1.jpg",
    images: ["/images/products/product-1.jpg", "/images/products/product-8.jpg"],
    seller: "UrbanEdge",
    sellerTier: "Pro",
    colors: [{ name: "Shadow", hex: "#2a2a2a", image: "/images/products/product-1.jpg" }, { name: "Fog", hex: "#c4c4c4", image: "/images/products/product-8.jpg" }],
    gender: "mens",
    category: "shoes",
    material: "mesh",
    sizes: [7, 8, 9, 10, 11, 12, 13],
    rating: 4.3,
    reviews: 26,
    description: "All-tonal trainer with a matte finish. The opposite of loud - it just quietly makes every outfit better.",
    inStock: true,
    collections: ["mens"],
  },
  {
    slug: "track-pant-mens",
    name: "Track Pant",
    price: 379,
    image: "/images/products/product-24.jpg",
    images: ["/images/products/product-24.jpg", "/images/products/product-25.jpg"],
    seller: "UrbanEdge",
    sellerTier: "Pro",
    colors: [{ name: "Black", hex: "#1a1a1a", image: "/images/products/product-24.jpg" }, { name: "Navy", hex: "#2a3a5c", image: "/images/products/product-25.jpg" }],
    gender: "mens",
    category: "apparel",
    material: "knit",
    sizes: [1, 2, 3, 4],
    rating: 4.4,
    reviews: 38,
    description: "Track pants with a tonal side stripe and tapered fit. Zip pockets, elastic cuff. The kind of track pant you wear out, not just to the gym.",
    inStock: true,
    collections: ["mens", "apparel"],
  },
  {
    slug: "heavyweight-crewneck",
    name: "Heavyweight Crewneck",
    price: 369,
    image: "/images/products/product-20.jpg",
    images: ["/images/products/product-20.jpg", "/images/products/product-21.jpg"],
    seller: "UrbanEdge",
    sellerTier: "Pro",
    badge: "NEW",
    colors: [{ name: "Washed Black", hex: "#2a2a2a", image: "/images/products/product-20.jpg" }, { name: "Cream", hex: "#f0ede6", image: "/images/products/product-21.jpg" }],
    gender: "mens",
    category: "apparel",
    material: "knit",
    sizes: [1, 2, 3, 4],
    rating: 4.5,
    reviews: 17,
    description: "420gsm heavyweight crewneck with a boxy cut. No hood, no zip, no logo - just a solid piece of knitwear that'll last years.",
    inStock: true,
    collections: ["mens", "apparel", "new-arrivals"],
  },
  {
    slug: "mesh-runner-low",
    name: "Mesh Runner Low",
    price: 419,
    image: "/images/products/product-9.jpg",
    images: ["/images/products/product-9.jpg", "/images/products/product-1.jpg"],
    seller: "UrbanEdge",
    sellerTier: "Pro",
    colors: [{ name: "White", hex: "#f0ede6", image: "/images/products/product-9.jpg" }, { name: "Black", hex: "#1a1a1a", image: "/images/products/product-1.jpg" }],
    gender: "mens",
    category: "shoes",
    material: "mesh",
    sizes: [7, 8, 9, 10, 11, 12],
    rating: 4.2,
    reviews: 14,
    description: "Low-profile mesh runner with a thin sole and minimal upper. For when you want to feel the ground under you.",
    inStock: true,
    collections: ["mens"],
  },
  {
    slug: "tech-vest",
    name: "Tech Vest",
    price: 359,
    image: "/images/products/product-22.jpg",
    seller: "UrbanEdge",
    sellerTier: "Pro",
    colors: [{ name: "Black", hex: "#1a1a1a", image: "/images/products/product-22.jpg" }],
    gender: "mens",
    category: "apparel",
    material: "mesh",
    sizes: [1, 2, 3, 4],
    rating: 4.1,
    reviews: 9,
    description: "Padded vest with a matte shell and zip pockets. Layer it over a hoodie or wear it solo. Technical streetwear done right.",
    inStock: true,
    collections: ["mens", "apparel"],
  },
  {
    slug: "knit-shorts-mens",
    name: "Knit Shorts",
    price: 249,
    image: "/images/products/product-24.jpg",
    images: ["/images/products/product-24.jpg", "/images/products/product-25.jpg"],
    seller: "UrbanEdge",
    sellerTier: "Pro",
    colors: [{ name: "Black", hex: "#1a1a1a", image: "/images/products/product-24.jpg" }, { name: "Olive", hex: "#5c6b4f", image: "/images/products/product-25.jpg" }],
    gender: "mens",
    category: "apparel",
    material: "knit",
    sizes: [1, 2, 3, 4],
    rating: 4.3,
    reviews: 21,
    description: "French terry shorts with a 7-inch inseam. Elastic waist, side pockets, clean lines. Summer staple.",
    inStock: true,
    collections: ["mens", "apparel"],
  },
  {
    slug: "cloud-runner-womens",
    name: "Cloud Runner",
    price: 479,
    image: "/images/products/product-12.jpg",
    images: ["/images/products/product-12.jpg", "/images/products/product-11.jpg", "/images/products/product-13.jpg"],
    seller: "Bella Donna",
    sellerTier: "Pro",
    badge: "BESTSELLER",
    colors: [{ name: "Blush Pink", hex: "#d4a5a5", image: "/images/products/product-12.jpg" }, { name: "Stone White", hex: "#f0ede6", image: "/images/products/product-11.jpg" }, { name: "Navy", hex: "#2a3a5c", image: "/images/products/product-13.jpg" }],
    gender: "womens",
    category: "shoes",
    material: "mesh",
    sizes: [5, 6, 7, 8, 9, 10, 11],
    rating: 4.8,
    reviews: 287,
    description: "A lightweight everyday runner with a breathable knit upper and cushioned sole. Built for comfort from morning to night.",
    inStock: true,
    collections: ["womens", "new-arrivals", "best-sellers"],
  },
  {
    slug: "breeze-slip-on",
    name: "Breeze Slip-On",
    price: 379,
    image: "/images/products/product-15.jpg",
    images: ["/images/products/product-15.jpg", "/images/products/product-12.jpg"],
    seller: "Bella Donna",
    sellerTier: "Pro",
    badge: "BESTSELLER",
    colors: [{ name: "Warm Sand", hex: "#c4b59a", image: "/images/products/product-15.jpg" }, { name: "Jet Black", hex: "#1a1a1a", image: "/images/products/product-15.jpg" }, { name: "Dusty Rose", hex: "#c49a9a", image: "/images/products/product-12.jpg" }],
    gender: "womens",
    category: "shoes",
    material: "tree-fiber",
    sizes: [5, 6, 7, 8, 9, 10],
    rating: 4.6,
    reviews: 421,
    description: "Slip into effortless style. A laceless design with a stretchy collar that hugs your foot just right.",
    inStock: true,
    collections: ["womens", "best-sellers"],
  },
  {
    slug: "aero-knit",
    name: "Aero Knit",
    price: 519,
    image: "/images/products/product-2.jpg",
    images: ["/images/products/product-2.jpg", "/images/products/product-5.jpg", "/images/products/product-13.jpg"],
    seller: "Bella Donna",
    sellerTier: "Pro",
    badge: "NEW",
    colors: [{ name: "Cloud White", hex: "#f5f0eb", image: "/images/products/product-2.jpg" }, { name: "Coral", hex: "#e07a5f", image: "/images/products/product-5.jpg" }, { name: "Deep Navy", hex: "#1e2d4a", image: "/images/products/product-13.jpg" }],
    gender: "womens",
    category: "shoes",
    material: "knit",
    sizes: [5, 6, 7, 8, 9, 10, 11],
    rating: 4.9,
    reviews: 203,
    description: "Featherlight and fully knitted for a sock-like fit. Your new go-to for everything.",
    inStock: true,
    collections: ["womens", "new-arrivals"],
  },
  {
    slug: "glide-flat",
    name: "Glide Flat",
    price: 419,
    image: "/images/products/product-15.jpg",
    images: ["/images/products/product-15.jpg", "/images/products/product-12.jpg", "/images/products/product-3.jpg"],
    seller: "Bella Donna",
    sellerTier: "Pro",
    badge: "BESTSELLER",
    colors: [{ name: "Jet Black", hex: "#1a1a1a", image: "/images/products/product-15.jpg" }, { name: "Ballet Pink", hex: "#e8c4c4", image: "/images/products/product-12.jpg" }, { name: "Forest", hex: "#3d5a3d", image: "/images/products/product-3.jpg" }],
    gender: "womens",
    category: "shoes",
    material: "tree-fiber",
    sizes: [5, 6, 7, 8, 9, 10],
    rating: 4.5,
    reviews: 267,
    description: "A sleek ballet flat with just enough support. Tree fiber keeps it cool and breathable all day.",
    inStock: true,
    collections: ["womens", "best-sellers"],
  },
  {
    slug: "metro-step",
    name: "Metro Step",
    price: 459,
    image: "/images/products/product-2.jpg",
    images: ["/images/products/product-2.jpg", "/images/products/product-16.jpg"],
    seller: "Bella Donna",
    sellerTier: "Pro",
    badge: "NEW",
    colors: [{ name: "Warm White", hex: "#f5efe6", image: "/images/products/product-2.jpg" }, { name: "Burgundy", hex: "#6b2a3d", image: "/images/products/product-16.jpg" }],
    gender: "womens",
    category: "shoes",
    material: "knit",
    sizes: [5, 6, 7, 8, 9, 10],
    rating: 4.3,
    reviews: 47,
    description: "Urban style meets all-day comfort. A modern silhouette with a cushioned platform sole.",
    inStock: true,
    collections: ["womens", "new-arrivals"],
  },
  {
    slug: "pullover-hoodie-womens",
    name: "Pullover Hoodie",
    price: 389,
    image: "/images/products/product-20.jpg",
    images: ["/images/products/product-20.jpg", "/images/products/product-21.jpg"],
    seller: "Bella Donna",
    sellerTier: "Pro",
    colors: [{ name: "Oatmeal", hex: "#c4b59a", image: "/images/products/product-20.jpg" }, { name: "Black", hex: "#1a1a1a", image: "/images/products/product-21.jpg" }],
    gender: "womens",
    category: "apparel",
    material: "wool",
    sizes: [1, 2, 3, 4],
    rating: 4.7,
    reviews: 134,
    description: "A cozy merino wool hoodie that regulates temperature naturally. Warm without the bulk.",
    inStock: true,
    collections: ["womens", "apparel"],
  },
  {
    slug: "jogger-pant-womens",
    name: "Jogger Pant",
    price: 349,
    image: "/images/products/product-24.jpg",
    images: ["/images/products/product-24.jpg", "/images/products/product-25.jpg"],
    seller: "Bella Donna",
    sellerTier: "Pro",
    colors: [{ name: "Black", hex: "#1a1a1a", image: "/images/products/product-24.jpg" }, { name: "Oatmeal", hex: "#c4b59a", image: "/images/products/product-25.jpg" }],
    gender: "womens",
    category: "apparel",
    material: "knit",
    sizes: [1, 2, 3, 4],
    rating: 4.6,
    reviews: 108,
    description: "Tapered joggers with a soft knit fabric that moves with you. Refined enough for the coffee shop.",
    inStock: true,
    collections: ["womens", "apparel"],
  },
  {
    slug: "cardigan-womens",
    name: "Cardigan",
    price: 429,
    image: "/images/products/product-22.jpg",
    images: ["/images/products/product-22.jpg", "/images/products/product-23.jpg"],
    seller: "Bella Donna",
    sellerTier: "Pro",
    badge: "NEW",
    colors: [{ name: "Oatmeal", hex: "#c4b59a", image: "/images/products/product-22.jpg" }, { name: "Charcoal", hex: "#333333", image: "/images/products/product-23.jpg" }],
    gender: "womens",
    category: "apparel",
    material: "wool",
    sizes: [1, 2, 3, 4],
    rating: 4.8,
    reviews: 74,
    description: "A relaxed-fit merino wool cardigan that layers effortlessly over anything.",
    inStock: true,
    collections: ["womens", "apparel", "new-arrivals"],
  },
  {
    slug: "silk-touch-flat",
    name: "Silk Touch Flat",
    price: 399,
    image: "/images/products/product-15.jpg",
    images: ["/images/products/product-15.jpg", "/images/products/product-10.jpg", "/images/products/product-12.jpg"],
    seller: "Bella Donna",
    sellerTier: "Pro",
    badge: "NEW",
    colors: [{ name: "Champagne", hex: "#e8d5b7", image: "/images/products/product-15.jpg" }, { name: "Black", hex: "#1a1a1a", image: "/images/products/product-10.jpg" }, { name: "Blush", hex: "#d4a5a5", image: "/images/products/product-12.jpg" }],
    gender: "womens",
    category: "shoes",
    material: "tree-fiber",
    sizes: [5, 6, 7, 8, 9, 10],
    rating: 4.7,
    reviews: 89,
    description: "Effortlessly refined flat with a pointed toe and cushioned footbed. The kind of shoe that elevates a simple outfit without trying. Silk-finish tree fiber upper with a barely-there weight that makes heels feel pointless.",
    inStock: true,
    collections: ["womens", "new-arrivals"],
  },
  {
    slug: "wrap-dress",
    name: "Wrap Dress",
    price: 499,
    image: "/images/products/product-22.jpg",
    images: ["/images/products/product-22.jpg", "/images/products/product-23.jpg"],
    seller: "Bella Donna",
    sellerTier: "Pro",
    badge: "NEW",
    colors: [{ name: "Navy", hex: "#2a3a5c", image: "/images/products/product-22.jpg" }, { name: "Black", hex: "#1a1a1a", image: "/images/products/product-23.jpg" }],
    gender: "womens",
    category: "apparel",
    material: "tree-fiber",
    sizes: [1, 2, 3, 4],
    rating: 4.8,
    reviews: 56,
    description: "A true wrap silhouette in eucalyptus tree fiber that drapes beautifully and breathes all day. From the morning meeting to the evening out - one piece, every occasion.",
    inStock: true,
    collections: ["womens", "apparel", "new-arrivals"],
  },
  {
    slug: "cloud-slip-on-ballet",
    name: "Cloud Slip-On Ballet",
    price: 359,
    image: "/images/products/product-12.jpg",
    images: ["/images/products/product-12.jpg", "/images/products/product-11.jpg", "/images/products/product-10.jpg"],
    seller: "Bella Donna",
    sellerTier: "Pro",
    colors: [{ name: "Rose", hex: "#c49a9a", image: "/images/products/product-12.jpg" }, { name: "Ivory", hex: "#f5f0eb", image: "/images/products/product-11.jpg" }, { name: "Black", hex: "#1a1a1a", image: "/images/products/product-10.jpg" }],
    gender: "womens",
    category: "shoes",
    material: "knit",
    sizes: [5, 6, 7, 8, 9, 10],
    rating: 4.5,
    reviews: 142,
    description: "The comfort of a sneaker in a ballet silhouette. Full-knit upper with a cushioned sole that makes all-day wear effortless. A wardrobe essential.",
    inStock: true,
    collections: ["womens"],
  },
  {
    slug: "oversized-blazer",
    name: "Oversized Blazer",
    price: 549,
    image: "/images/products/product-22.jpg",
    images: ["/images/products/product-22.jpg", "/images/products/product-23.jpg"],
    seller: "Bella Donna",
    sellerTier: "Pro",
    colors: [{ name: "Charcoal", hex: "#333333", image: "/images/products/product-22.jpg" }, { name: "Cream", hex: "#f0ede6", image: "/images/products/product-23.jpg" }],
    gender: "womens",
    category: "apparel",
    material: "wool",
    sizes: [1, 2, 3, 4],
    rating: 4.6,
    reviews: 37,
    description: "Relaxed oversized blazer in a soft wool blend. Structured enough for meetings, relaxed enough for brunch. The single-button closure and patch pockets give it that effortless polish.",
    inStock: true,
    collections: ["womens", "apparel"],
  },
  {
    slug: "linen-tee-womens",
    name: "Linen Tee",
    price: 229,
    image: "/images/products/product-17.jpg",
    images: ["/images/products/product-17.jpg", "/images/products/product-18.jpg", "/images/products/product-19.jpg"],
    seller: "Bella Donna",
    sellerTier: "Pro",
    colors: [{ name: "White", hex: "#f0ede6", image: "/images/products/product-17.jpg" }, { name: "Sky Blue", hex: "#87CEEB", image: "/images/products/product-18.jpg" }, { name: "Blush", hex: "#d4a5a5", image: "/images/products/product-19.jpg" }],
    gender: "womens",
    category: "apparel",
    material: "tree-fiber",
    sizes: [1, 2, 3, 4],
    rating: 4.4,
    reviews: 98,
    description: "A breezy linen-blend tee with a slightly cropped hem. The perfect summer layer - it gets softer with every wash.",
    inStock: true,
    collections: ["womens", "apparel"],
  },
  {
    slug: "ankle-boot-womens",
    name: "Ankle Boot",
    price: 549,
    image: "/images/products/product-10.jpg",
    images: ["/images/products/product-10.jpg", "/images/products/product-14.jpg"],
    seller: "Bella Donna",
    sellerTier: "Pro",
    badge: "NEW",
    colors: [{ name: "Black", hex: "#1a1a1a", image: "/images/products/product-10.jpg" }, { name: "Cognac", hex: "#8b4513", image: "/images/products/product-14.jpg" }],
    gender: "womens",
    category: "shoes",
    material: "leather",
    sizes: [5, 6, 7, 8, 9, 10],
    rating: 4.6,
    reviews: 43,
    description: "Refined ankle boot in buttery-soft leather with a low block heel. The kind of boot that carries you from morning coffee to evening drinks without a wardrobe change. Cushioned insole for all-day wear.",
    inStock: true,
    collections: ["womens", "new-arrivals"],
  },
  {
    slug: "knit-loafer-womens",
    name: "Knit Loafer",
    price: 389,
    image: "/images/products/product-10.jpg",
    images: ["/images/products/product-10.jpg", "/images/products/product-15.jpg", "/images/products/product-13.jpg"],
    seller: "Bella Donna",
    sellerTier: "Pro",
    colors: [{ name: "Black", hex: "#1a1a1a", image: "/images/products/product-10.jpg" }, { name: "Taupe", hex: "#8b7d6b", image: "/images/products/product-15.jpg" }, { name: "Navy", hex: "#2a3a5c", image: "/images/products/product-13.jpg" }],
    gender: "womens",
    category: "shoes",
    material: "knit",
    sizes: [5, 6, 7, 8, 9, 10],
    rating: 4.5,
    reviews: 67,
    description: "Full-knit loafer that feels like a slipper but looks like you have your life together. The square toe and structured silhouette elevate any outfit.",
    inStock: true,
    collections: ["womens"],
  },
  {
    slug: "cropped-jacket-womens",
    name: "Cropped Jacket",
    price: 499,
    image: "/images/products/product-22.jpg",
    images: ["/images/products/product-22.jpg", "/images/products/product-23.jpg"],
    seller: "Bella Donna",
    sellerTier: "Pro",
    colors: [{ name: "Cream", hex: "#f0ede6", image: "/images/products/product-22.jpg" }, { name: "Black", hex: "#1a1a1a", image: "/images/products/product-23.jpg" }],
    gender: "womens",
    category: "apparel",
    material: "wool",
    sizes: [1, 2, 3, 4],
    rating: 4.7,
    reviews: 29,
    description: "Cropped wool-blend jacket with a collarless neckline and raw-edge trim. The piece that makes jeans and a tee look intentional. Unlined for a lightweight feel.",
    inStock: true,
    collections: ["womens", "apparel"],
  },
  {
    slug: "silk-cami",
    name: "Silk Cami",
    price: 299,
    image: "/images/products/product-17.jpg",
    images: ["/images/products/product-17.jpg", "/images/products/product-18.jpg", "/images/products/product-19.jpg"],
    seller: "Bella Donna",
    sellerTier: "Pro",
    badge: "NEW",
    colors: [{ name: "Champagne", hex: "#e8d5b7", image: "/images/products/product-17.jpg" }, { name: "Black", hex: "#1a1a1a", image: "/images/products/product-18.jpg" }, { name: "Ivory", hex: "#f5f0eb", image: "/images/products/product-19.jpg" }],
    gender: "womens",
    category: "apparel",
    material: "tree-fiber",
    sizes: [1, 2, 3, 4],
    rating: 4.8,
    reviews: 51,
    description: "Silk-finish camisole with adjustable straps and a cowl neckline. Layer it under a blazer or let it do the talking on its own. The drape is everything.",
    inStock: true,
    collections: ["womens", "apparel", "new-arrivals"],
  },
  {
    slug: "wide-leg-pant-womens",
    name: "Wide Leg Pant",
    price: 429,
    image: "/images/products/product-24.jpg",
    images: ["/images/products/product-24.jpg", "/images/products/product-25.jpg"],
    seller: "Bella Donna",
    sellerTier: "Pro",
    colors: [{ name: "Black", hex: "#1a1a1a", image: "/images/products/product-24.jpg" }, { name: "Navy", hex: "#2a3a5c", image: "/images/products/product-25.jpg" }],
    gender: "womens",
    category: "apparel",
    material: "tree-fiber",
    sizes: [1, 2, 3, 4],
    rating: 4.6,
    reviews: 34,
    description: "High-waisted wide-leg trousers in a flowing tree-fiber fabric. The silhouette of tailored trousers with the comfort of pajamas. A wardrobe anchor.",
    inStock: true,
    collections: ["womens", "apparel"],
  },
  {
    slug: "platform-slip-on-womens",
    name: "Platform Slip-On",
    price: 439,
    image: "/images/products/product-2.jpg",
    images: ["/images/products/product-2.jpg", "/images/products/product-10.jpg"],
    seller: "Bella Donna",
    sellerTier: "Pro",
    colors: [{ name: "White", hex: "#f0ede6", image: "/images/products/product-2.jpg" }, { name: "Black", hex: "#1a1a1a", image: "/images/products/product-10.jpg" }],
    gender: "womens",
    category: "shoes",
    material: "knit",
    sizes: [5, 6, 7, 8, 9, 10],
    rating: 4.4,
    reviews: 21,
    description: "Platform slip-on with a sculpted sole and full-knit upper. Adds height without the heel. Statement piece with sneaker-level comfort.",
    inStock: true,
    collections: ["womens"],
  },
  {
    slug: "wool-scarf-womens",
    name: "Wool Scarf",
    price: 249,
    image: "/images/products/product-30.jpg",
    images: ["/images/products/product-30.jpg", "/images/products/product-31.jpg"],
    seller: "Bella Donna",
    sellerTier: "Pro",
    colors: [{ name: "Camel", hex: "#c4a060", image: "/images/products/product-30.jpg" }, { name: "Charcoal", hex: "#333333", image: "/images/products/product-31.jpg" }],
    gender: "womens",
    category: "accessories",
    material: "wool",
    sizes: [0],
    rating: 4.7,
    reviews: 18,
    description: "Oversized merino wool scarf that doubles as a wrap. The kind of accessory that turns a simple coat into an outfit.",
    inStock: true,
    collections: ["womens", "accessories"],
  },
  {
    slug: "dash-sport-womens",
    name: "Dash Sport",
    price: 579,
    image: "/images/products/product-5.jpg",
    images: ["/images/products/product-5.jpg", "/images/products/product-10.jpg"],
    seller: "SportPeak",
    sellerTier: "Pro",
    badge: "NEW",
    colors: [{ name: "Coral Pink", hex: "#e07a7a", image: "/images/products/product-5.jpg" }, { name: "Black", hex: "#1a1a1a", image: "/images/products/product-10.jpg" }],
    gender: "womens",
    category: "shoes",
    material: "mesh",
    sizes: [5, 6, 7, 8, 9, 10, 11],
    rating: 4.4,
    reviews: 189,
    description: "Engineered for performance. Responsive cushioning and a breathable upper for your best run yet.",
    inStock: true,
    collections: ["womens", "new-arrivals"],
  },
  {
    slug: "tempo-trainer",
    name: "Tempo Trainer",
    price: 359,
    originalPrice: 519,
    image: "/images/products/product-7.jpg",
    images: ["/images/products/product-7.jpg", "/images/products/product-16.jpg"],
    seller: "SportPeak",
    sellerTier: "Pro",
    badge: "SALE",
    colors: [{ name: "Red", hex: "#9e4040", image: "/images/products/product-7.jpg" }, { name: "Grey", hex: "#8a8a8a", image: "/images/products/product-16.jpg" }],
    gender: "mens",
    category: "shoes",
    material: "mesh",
    sizes: [7, 8, 9, 10, 11, 12],
    rating: 4.1,
    reviews: 223,
    description: "A versatile cross-trainer that handles everything from the gym to the street.",
    inStock: true,
    collections: ["mens", "sale"],
  },
  {
    slug: "tempo-trainer-womens",
    name: "Tempo Trainer",
    price: 359,
    originalPrice: 519,
    image: "/images/products/product-3.jpg",
    images: ["/images/products/product-3.jpg", "/images/products/product-10.jpg"],
    seller: "SportPeak",
    sellerTier: "Pro",
    badge: "SALE",
    colors: [{ name: "Sage", hex: "#8a9a7a", image: "/images/products/product-3.jpg" }, { name: "Black", hex: "#1a1a1a", image: "/images/products/product-10.jpg" }],
    gender: "womens",
    category: "shoes",
    material: "mesh",
    sizes: [5, 6, 7, 8, 9, 10],
    rating: 3.9,
    reviews: 167,
    description: "A versatile cross-trainer that handles everything from the gym to the street.",
    inStock: true,
    collections: ["womens", "sale"],
  },
  {
    slug: "performance-sock",
    name: "Performance Sock",
    price: 79,
    image: "/images/products/product-26.jpg",
    images: ["/images/products/product-26.jpg", "/images/products/product-27.jpg"],
    seller: "SportPeak",
    sellerTier: "Pro",
    badge: "NEW",
    colors: [{ name: "Black", hex: "#1a1a1a", image: "/images/products/product-26.jpg" }, { name: "Grey", hex: "#8a8a8a", image: "/images/products/product-27.jpg" }],
    gender: "unisex",
    category: "accessories",
    material: "mesh",
    sizes: [1, 2, 3, 4],
    rating: 4.7,
    reviews: 89,
    description: "Engineered for active days with targeted cushioning and ventilation zones.",
    inStock: true,
    collections: ["mens", "womens", "socks", "new-arrivals"],
  },
  {
    slug: "velocity-runner",
    name: "Velocity Runner",
    price: 549,
    image: "/images/products/product-6.jpg",
    images: ["/images/products/product-6.jpg", "/images/products/product-1.jpg", "/images/products/product-9.jpg"],
    seller: "SportPeak",
    sellerTier: "Pro",
    badge: "NEW",
    colors: [{ name: "Volt", hex: "#c4ff00", image: "/images/products/product-6.jpg" }, { name: "Black", hex: "#1a1a1a", image: "/images/products/product-1.jpg" }, { name: "White", hex: "#f0ede6", image: "/images/products/product-9.jpg" }],
    gender: "mens",
    category: "shoes",
    material: "mesh",
    sizes: [7, 8, 9, 10, 11, 12, 13],
    rating: 4.6,
    reviews: 74,
    description: "Race-day speed in an everyday package. Carbon-infused plate for propulsion, ultra-lightweight mesh for breathability, and a stack height that eats kilometers. This is the shoe that makes your tempo run feel like recovery.",
    inStock: true,
    collections: ["mens", "new-arrivals"],
  },
  {
    slug: "velocity-runner-womens",
    name: "Velocity Runner W",
    price: 549,
    image: "/images/products/product-5.jpg",
    images: ["/images/products/product-5.jpg", "/images/products/product-11.jpg"],
    seller: "SportPeak",
    sellerTier: "Pro",
    badge: "NEW",
    colors: [{ name: "Coral", hex: "#e07a5f", image: "/images/products/product-5.jpg" }, { name: "White", hex: "#f0ede6", image: "/images/products/product-11.jpg" }],
    gender: "womens",
    category: "shoes",
    material: "mesh",
    sizes: [5, 6, 7, 8, 9, 10, 11],
    rating: 4.7,
    reviews: 62,
    description: "Race-day speed in an everyday package. Carbon-infused plate for propulsion, ultra-lightweight mesh that breathes, and a stack height built for distance. Your new PB starts here.",
    inStock: true,
    collections: ["womens", "new-arrivals"],
  },
  {
    slug: "trail-grip",
    name: "Trail Grip",
    price: 499,
    image: "/images/products/product-3.jpg",
    images: ["/images/products/product-3.jpg", "/images/products/product-7.jpg"],
    seller: "SportPeak",
    sellerTier: "Pro",
    colors: [{ name: "Forest", hex: "#3d5a3d", image: "/images/products/product-3.jpg" }, { name: "Black", hex: "#1a1a1a", image: "/images/products/product-7.jpg" }],
    gender: "mens",
    category: "shoes",
    material: "mesh",
    sizes: [7, 8, 9, 10, 11, 12, 13],
    rating: 4.4,
    reviews: 45,
    description: "Aggressive trail runner with a Vibram Megagrip outsole that handles mud, rock, and everything between. Waterproof membrane keeps you dry. Built for race day in the mountains.",
    inStock: true,
    collections: ["mens"],
  },
  {
    slug: "power-trainer",
    name: "Power Trainer",
    price: 449,
    image: "/images/products/product-1.jpg",
    images: ["/images/products/product-1.jpg", "/images/products/product-8.jpg", "/images/products/product-7.jpg"],
    seller: "SportPeak",
    sellerTier: "Pro",
    colors: [{ name: "Black", hex: "#1a1a1a", image: "/images/products/product-1.jpg" }, { name: "Grey", hex: "#8a8a8a", image: "/images/products/product-8.jpg" }, { name: "Red", hex: "#9e4040", image: "/images/products/product-7.jpg" }],
    gender: "mens",
    category: "shoes",
    material: "mesh",
    sizes: [7, 8, 9, 10, 11, 12, 13],
    rating: 4.5,
    reviews: 156,
    description: "Flat sole, wide base, zero drop. Built for lifting, HIIT, and everything that needs a stable platform. The outsole wraps up the sidewall for rope climbs.",
    inStock: true,
    collections: ["mens", "best-sellers"],
  },
  {
    slug: "sprint-tight-womens",
    name: "Sprint Tight",
    price: 399,
    image: "/images/products/product-24.jpg",
    images: ["/images/products/product-24.jpg", "/images/products/product-25.jpg"],
    seller: "SportPeak",
    sellerTier: "Pro",
    colors: [{ name: "Black", hex: "#1a1a1a", image: "/images/products/product-24.jpg" }, { name: "Navy", hex: "#2a3a5c", image: "/images/products/product-25.jpg" }],
    gender: "womens",
    category: "apparel",
    material: "knit",
    sizes: [1, 2, 3, 4],
    rating: 4.6,
    reviews: 83,
    description: "High-waisted running tight with compression zones and a side pocket that actually fits your phone. Squat-proof, sweat-wicking, and designed for movement.",
    inStock: true,
    collections: ["womens", "apparel"],
  },
  {
    slug: "training-tee",
    name: "Training Tee",
    price: 199,
    image: "/images/products/product-17.jpg",
    images: ["/images/products/product-17.jpg", "/images/products/product-18.jpg"],
    seller: "SportPeak",
    sellerTier: "Pro",
    colors: [{ name: "Black", hex: "#1a1a1a", image: "/images/products/product-17.jpg" }, { name: "Grey", hex: "#8a8a8a", image: "/images/products/product-18.jpg" }],
    gender: "mens",
    category: "apparel",
    material: "mesh",
    sizes: [1, 2, 3, 4],
    rating: 4.3,
    reviews: 67,
    description: "Quick-dry training tee with mesh ventilation panels. Designed to move sweat, not trap it. Athletic fit that stays out of the way during lifts.",
    inStock: true,
    collections: ["mens", "apparel"],
  },
  {
    slug: "endurance-runner",
    name: "Endurance Runner",
    price: 479,
    image: "/images/products/product-8.jpg",
    images: ["/images/products/product-8.jpg", "/images/products/product-1.jpg"],
    seller: "SportPeak",
    sellerTier: "Pro",
    colors: [{ name: "Grey", hex: "#8a8a8a", image: "/images/products/product-8.jpg" }, { name: "Black", hex: "#1a1a1a", image: "/images/products/product-1.jpg" }],
    gender: "mens",
    category: "shoes",
    material: "mesh",
    sizes: [7, 8, 9, 10, 11, 12, 13],
    rating: 4.3,
    reviews: 41,
    description: "Built for the long run. High-stack cushioning with a durable rubber outsole that lasts 800+ km. Neutral ride, smooth transitions, and enough foam to make marathon distance feel comfortable.",
    inStock: true,
    collections: ["mens"],
  },
  {
    slug: "recovery-slide",
    name: "Recovery Slide",
    price: 249,
    image: "/images/products/product-16.jpg",
    images: ["/images/products/product-16.jpg", "/images/products/product-8.jpg"],
    seller: "SportPeak",
    sellerTier: "Pro",
    colors: [{ name: "Black", hex: "#1a1a1a", image: "/images/products/product-16.jpg" }, { name: "Grey", hex: "#8a8a8a", image: "/images/products/product-8.jpg" }],
    gender: "unisex",
    category: "shoes",
    material: "mesh",
    sizes: [6, 7, 8, 9, 10, 11, 12],
    rating: 4.5,
    reviews: 87,
    description: "Post-workout recovery slide with max cushioning and arch support. The foam is so soft it feels like stepping on a cloud after a hard session.",
    inStock: true,
    collections: ["mens", "womens"],
  },
  {
    slug: "track-jacket-mens",
    name: "Track Jacket",
    price: 449,
    image: "/images/products/product-22.jpg",
    images: ["/images/products/product-22.jpg", "/images/products/product-23.jpg"],
    seller: "SportPeak",
    sellerTier: "Pro",
    badge: "NEW",
    colors: [{ name: "Black", hex: "#1a1a1a", image: "/images/products/product-22.jpg" }, { name: "Navy", hex: "#2a3a5c", image: "/images/products/product-23.jpg" }],
    gender: "mens",
    category: "apparel",
    material: "mesh",
    sizes: [1, 2, 3, 4],
    rating: 4.4,
    reviews: 31,
    description: "Lightweight track jacket with mesh ventilation and zip pockets. Designed for warm-ups but sharp enough for the street. Reflective details for early-morning runs.",
    inStock: true,
    collections: ["mens", "apparel", "new-arrivals"],
  },
  {
    slug: "running-short-mens",
    name: "Running Short",
    price: 249,
    image: "/images/products/product-24.jpg",
    images: ["/images/products/product-24.jpg", "/images/products/product-25.jpg"],
    seller: "SportPeak",
    sellerTier: "Pro",
    colors: [{ name: "Black", hex: "#1a1a1a", image: "/images/products/product-24.jpg" }, { name: "Navy", hex: "#2a3a5c", image: "/images/products/product-25.jpg" }],
    gender: "mens",
    category: "apparel",
    material: "mesh",
    sizes: [1, 2, 3, 4],
    rating: 4.3,
    reviews: 52,
    description: "5-inch running shorts with a built-in liner and zip pocket at the back. Split hem for full range of motion. Quick-dry fabric that handles sweat.",
    inStock: true,
    collections: ["mens", "apparel"],
  },
  {
    slug: "stability-trainer-womens",
    name: "Stability Trainer W",
    price: 499,
    image: "/images/products/product-11.jpg",
    images: ["/images/products/product-11.jpg", "/images/products/product-10.jpg"],
    seller: "SportPeak",
    sellerTier: "Pro",
    colors: [{ name: "Grey/Pink", hex: "#8a8a8a", image: "/images/products/product-11.jpg" }, { name: "Black", hex: "#1a1a1a", image: "/images/products/product-10.jpg" }],
    gender: "womens",
    category: "shoes",
    material: "mesh",
    sizes: [5, 6, 7, 8, 9, 10, 11],
    rating: 4.5,
    reviews: 38,
    description: "Stability running shoe with medial post support and a guide rail system. Prevents overpronation without feeling clunky. Designed specifically for the female foot.",
    inStock: true,
    collections: ["womens"],
  },
  {
    slug: "classic-walker",
    name: "Classic Walker",
    price: 199,
    image: "/images/products/product-8.jpg",
    images: ["/images/products/product-8.jpg", "/images/products/product-16.jpg", "/images/products/product-9.jpg"],
    seller: "EcoThreads",
    sellerTier: "Pro",
    badge: "BESTSELLER",
    colors: [{ name: "Natural Grey", hex: "#9a9a9a", image: "/images/products/product-8.jpg" }, { name: "Midnight", hex: "#1a1a2e", image: "/images/products/product-16.jpg" }, { name: "Cream", hex: "#f0ede6", image: "/images/products/product-9.jpg" }],
    gender: "mens",
    category: "shoes",
    material: "wool",
    sizes: [7, 8, 9, 10, 11, 12, 13],
    rating: 4.7,
    reviews: 487,
    description: "The shoe that started it all. Soft wool, simple design, endlessly comfortable.",
    inStock: true,
    collections: ["mens", "best-sellers"],
  },
  {
    slug: "classic-walker-womens",
    name: "Classic Walker",
    price: 199,
    image: "/images/products/product-12.jpg",
    images: ["/images/products/product-12.jpg", "/images/products/product-11.jpg", "/images/products/product-2.jpg"],
    seller: "EcoThreads",
    sellerTier: "Pro",
    colors: [{ name: "Lavender", hex: "#b5a7c9", image: "/images/products/product-12.jpg" }, { name: "Natural Grey", hex: "#9a9a9a", image: "/images/products/product-11.jpg" }, { name: "Cream", hex: "#f0ede6", image: "/images/products/product-2.jpg" }],
    gender: "womens",
    category: "shoes",
    material: "wool",
    sizes: [5, 6, 7, 8, 9, 10],
    rating: 4.6,
    reviews: 392,
    description: "The shoe that started it all. Soft wool, simple design, endlessly comfortable.",
    inStock: true,
    collections: ["womens", "best-sellers"],
  },
  {
    slug: "coast-slide",
    name: "Coast Slide",
    price: 109,
    image: "/images/products/product-8.jpg",
    images: ["/images/products/product-8.jpg", "/images/products/product-16.jpg"],
    seller: "EcoThreads",
    sellerTier: "Pro",
    badge: "NEW",
    colors: [{ name: "Sand", hex: "#c4b59a", image: "/images/products/product-8.jpg" }, { name: "Black", hex: "#1a1a1a", image: "/images/products/product-16.jpg" }],
    gender: "unisex",
    category: "shoes",
    material: "tree-fiber",
    sizes: [6, 7, 8, 9, 10, 11, 12],
    rating: 4.2,
    reviews: 347,
    description: "The easiest shoe you'll ever own. Slip on, step out, done.",
    inStock: true,
    collections: ["mens", "womens", "new-arrivals"],
  },
  {
    slug: "classic-tee-mens",
    name: "Classic Tee",
    price: 89,
    image: "/images/products/product-17.jpg",
    images: ["/images/products/product-17.jpg", "/images/products/product-18.jpg", "/images/products/product-19.jpg"],
    seller: "EcoThreads",
    sellerTier: "Pro",
    badge: "NEW",
    colors: [{ name: "White", hex: "#f0ede6", image: "/images/products/product-17.jpg" }, { name: "Black", hex: "#1a1a1a", image: "/images/products/product-18.jpg" }, { name: "Olive", hex: "#5c6b4f", image: "/images/products/product-19.jpg" }],
    gender: "mens",
    category: "apparel",
    material: "tree-fiber",
    sizes: [1, 2, 3, 4],
    rating: 4.6,
    reviews: 175,
    description: "Soft tee from eucalyptus fiber. Light, breathable, ready for anything.",
    inStock: true,
    collections: ["mens", "apparel", "new-arrivals"],
  },
  {
    slug: "classic-tee-womens",
    name: "Classic Tee",
    price: 89,
    image: "/images/products/product-17.jpg",
    images: ["/images/products/product-17.jpg", "/images/products/product-18.jpg", "/images/products/product-19.jpg"],
    seller: "EcoThreads",
    sellerTier: "Pro",
    badge: "NEW",
    colors: [{ name: "White", hex: "#f0ede6", image: "/images/products/product-17.jpg" }, { name: "Blush", hex: "#d4a5a5", image: "/images/products/product-18.jpg" }, { name: "Black", hex: "#1a1a1a", image: "/images/products/product-19.jpg" }],
    gender: "womens",
    category: "apparel",
    material: "tree-fiber",
    sizes: [1, 2, 3, 4],
    rating: 4.7,
    reviews: 193,
    description: "Soft tee from eucalyptus fiber. Light, breathable, ready for anything.",
    inStock: true,
    collections: ["womens", "apparel", "new-arrivals"],
  },
  {
    slug: "day-walker",
    name: "Day Walker",
    price: 149,
    image: "/images/products/product-8.jpg",
    images: ["/images/products/product-8.jpg", "/images/products/product-6.jpg"],
    seller: "EcoThreads",
    sellerTier: "Pro",
    colors: [{ name: "Grey", hex: "#9a9a9a", image: "/images/products/product-8.jpg" }, { name: "Navy", hex: "#2a3a5c", image: "/images/products/product-6.jpg" }],
    gender: "unisex",
    category: "shoes",
    material: "knit",
    sizes: [6, 7, 8, 9, 10, 11, 12],
    rating: 4.4,
    reviews: 67,
    description: "Simple everyday walker. Knit upper, foam sole, nothing fancy. Just comfortable.",
    inStock: true,
    collections: ["mens", "womens"],
  },
  {
    slug: "basic-hoodie-unisex",
    name: "Basic Hoodie",
    price: 149,
    image: "/images/products/product-20.jpg",
    images: ["/images/products/product-20.jpg", "/images/products/product-21.jpg"],
    seller: "EcoThreads",
    sellerTier: "Pro",
    colors: [{ name: "Grey", hex: "#8a8a8a", image: "/images/products/product-20.jpg" }, { name: "Black", hex: "#1a1a1a", image: "/images/products/product-21.jpg" }, { name: "Navy", hex: "#2a3a5c", image: "/images/products/product-20.jpg" }],
    gender: "unisex",
    category: "apparel",
    material: "knit",
    sizes: [1, 2, 3, 4],
    rating: 4.5,
    reviews: 89,
    description: "No-frills hoodie. Good fabric, good fit, good price. That's it.",
    inStock: true,
    collections: ["mens", "womens", "apparel"],
  },
  {
    slug: "canvas-slip-on",
    name: "Canvas Slip-On",
    price: 119,
    image: "/images/products/product-9.jpg",
    images: ["/images/products/product-9.jpg", "/images/products/product-16.jpg"],
    seller: "EcoThreads",
    sellerTier: "Pro",
    colors: [{ name: "White", hex: "#f0ede6", image: "/images/products/product-9.jpg" }, { name: "Black", hex: "#1a1a1a", image: "/images/products/product-16.jpg" }],
    gender: "unisex",
    category: "shoes",
    material: "tree-fiber",
    sizes: [6, 7, 8, 9, 10, 11, 12],
    rating: 4.2,
    reviews: 134,
    description: "Canvas slip-on for summer. Elastic gusset, vulcanized sole. Simple.",
    inStock: true,
    collections: ["mens", "womens"],
  },
  {
    slug: "jogger-basic",
    name: "Jogger Basic",
    price: 129,
    image: "/images/products/product-24.jpg",
    images: ["/images/products/product-24.jpg", "/images/products/product-25.jpg"],
    seller: "EcoThreads",
    sellerTier: "Pro",
    colors: [{ name: "Black", hex: "#1a1a1a", image: "/images/products/product-24.jpg" }, { name: "Grey", hex: "#8a8a8a", image: "/images/products/product-25.jpg" }],
    gender: "unisex",
    category: "apparel",
    material: "knit",
    sizes: [1, 2, 3, 4],
    rating: 4.3,
    reviews: 56,
    description: "Everyday joggers. Elastic waist, tapered leg, side pockets. Nothing more, nothing less.",
    inStock: true,
    collections: ["mens", "womens", "apparel"],
  },
  {
    slug: "weekend-sneaker",
    name: "Weekend Sneaker",
    price: 179,
    image: "/images/products/product-9.jpg",
    images: ["/images/products/product-9.jpg", "/images/products/product-8.jpg", "/images/products/product-6.jpg"],
    seller: "EcoThreads",
    sellerTier: "Pro",
    colors: [{ name: "White", hex: "#f0ede6", image: "/images/products/product-9.jpg" }, { name: "Grey", hex: "#9a9a9a", image: "/images/products/product-8.jpg" }, { name: "Navy", hex: "#2a3a5c", image: "/images/products/product-6.jpg" }],
    gender: "unisex",
    category: "shoes",
    material: "knit",
    sizes: [6, 7, 8, 9, 10, 11, 12],
    rating: 4.3,
    reviews: 45,
    description: "Low-key sneaker for lazy weekends and coffee runs. Knit upper, comfy sole.",
    inStock: true,
    collections: ["mens", "womens"],
  },
  {
    slug: "basic-crew-sock",
    name: "Basic Crew Sock",
    price: 29,
    image: "/images/products/product-26.jpg",
    images: ["/images/products/product-26.jpg", "/images/products/product-27.jpg"],
    seller: "EcoThreads",
    sellerTier: "Pro",
    colors: [{ name: "White", hex: "#f0ede6", image: "/images/products/product-26.jpg" }, { name: "Black", hex: "#1a1a1a", image: "/images/products/product-27.jpg" }],
    gender: "unisex",
    category: "accessories",
    material: "tree-fiber",
    sizes: [1, 2, 3, 4],
    rating: 4.2,
    reviews: 78,
    description: "Basic crew socks. Cotton blend, reinforced toe and heel. 3-pack.",
    inStock: true,
    collections: ["mens", "womens", "socks"],
  },
  {
    slug: "everyday-flat",
    name: "Everyday Flat",
    price: 139,
    image: "/images/products/product-10.jpg",
    images: ["/images/products/product-10.jpg", "/images/products/product-15.jpg"],
    seller: "EcoThreads",
    sellerTier: "Pro",
    colors: [{ name: "Black", hex: "#1a1a1a", image: "/images/products/product-10.jpg" }, { name: "Beige", hex: "#c4b59a", image: "/images/products/product-15.jpg" }],
    gender: "womens",
    category: "shoes",
    material: "knit",
    sizes: [5, 6, 7, 8, 9, 10],
    rating: 4.3,
    reviews: 43,
    description: "Simple knit flat for everyday. Cushioned insole, flexible sole. Nothing fancy, just comfortable.",
    inStock: true,
    collections: ["womens"],
  },
  {
    slug: "lab-runner-001",
    name: "Lab Runner 001",
    price: 249,
    image: "/images/products/product-9.jpg",
    images: ["/images/products/product-9.jpg", "/images/products/product-1.jpg", "/images/products/product-8.jpg"],
    seller: "Sneaker Lab",
    sellerTier: "Pro",
    colors: [{ name: "White", hex: "#f0ede6", image: "/images/products/product-9.jpg" }, { name: "Black", hex: "#1a1a1a", image: "/images/products/product-1.jpg" }, { name: "Grey", hex: "#8a8a8a", image: "/images/products/product-8.jpg" }],
    gender: "mens",
    category: "shoes",
    material: "mesh",
    sizes: [7, 8, 9, 10, 11, 12],
    rating: 4.5,
    reviews: 34,
    description: "Clean runner with a minimal profile. Hand-picked by the Lab team for its silhouette and comfort balance.",
    inStock: true,
    collections: ["mens", "new-arrivals"],
  },
  {
    slug: "lab-runner-002",
    name: "Lab Runner 002",
    price: 249,
    image: "/images/products/product-12.jpg",
    images: ["/images/products/product-12.jpg", "/images/products/product-11.jpg"],
    seller: "Sneaker Lab",
    sellerTier: "Pro",
    colors: [{ name: "Blush", hex: "#d4a5a5", image: "/images/products/product-12.jpg" }, { name: "White", hex: "#f0ede6", image: "/images/products/product-11.jpg" }],
    gender: "womens",
    category: "shoes",
    material: "mesh",
    sizes: [5, 6, 7, 8, 9, 10],
    rating: 4.6,
    reviews: 28,
    description: "Tonal runner in a women's-specific last. Curated by the Lab for clean lines and all-day comfort.",
    inStock: true,
    collections: ["womens", "new-arrivals"],
  },
  {
    slug: "lab-trainer-classic",
    name: "Lab Trainer Classic",
    price: 219,
    image: "/images/products/product-9.jpg",
    images: ["/images/products/product-9.jpg", "/images/products/product-1.jpg"],
    seller: "Sneaker Lab",
    sellerTier: "Pro",
    colors: [{ name: "White", hex: "#f0ede6", image: "/images/products/product-9.jpg" }, { name: "Black", hex: "#1a1a1a", image: "/images/products/product-1.jpg" }],
    gender: "mens",
    category: "shoes",
    material: "leather",
    sizes: [7, 8, 9, 10, 11, 12, 13],
    rating: 4.4,
    reviews: 72,
    description: "Leather trainer with a retro profile. The kind of sneaker that goes with everything - jeans, chinos, whatever.",
    inStock: true,
    collections: ["mens", "best-sellers"],
  },
  {
    slug: "lab-knit-runner",
    name: "Lab Knit Runner",
    price: 229,
    image: "/images/products/product-8.jpg",
    images: ["/images/products/product-8.jpg", "/images/products/product-6.jpg"],
    seller: "Sneaker Lab",
    sellerTier: "Pro",
    colors: [{ name: "Grey", hex: "#9a9a9a", image: "/images/products/product-8.jpg" }, { name: "Navy", hex: "#2a3a5c", image: "/images/products/product-6.jpg" }],
    gender: "unisex",
    category: "shoes",
    material: "knit",
    sizes: [6, 7, 8, 9, 10, 11, 12],
    rating: 4.3,
    reviews: 41,
    description: "Full-knit runner, zero waste construction. Sock-like fit, responsive sole. Lab-selected.",
    inStock: true,
    collections: ["mens", "womens"],
  },
  {
    slug: "lab-high-top",
    name: "Lab High Top",
    price: 239,
    image: "/images/products/product-1.jpg",
    images: ["/images/products/product-1.jpg", "/images/products/product-9.jpg"],
    seller: "Sneaker Lab",
    sellerTier: "Pro",
    badge: "NEW",
    colors: [{ name: "Black", hex: "#1a1a1a", image: "/images/products/product-1.jpg" }, { name: "White", hex: "#f0ede6", image: "/images/products/product-9.jpg" }],
    gender: "mens",
    category: "shoes",
    material: "leather",
    sizes: [7, 8, 9, 10, 11, 12],
    rating: 4.2,
    reviews: 19,
    description: "High-top in full-grain leather. Padded collar, flat sole, statement piece. Not for blending in.",
    inStock: true,
    collections: ["mens", "new-arrivals"],
  },
  {
    slug: "lab-suede-trainer",
    name: "Lab Suede Trainer",
    price: 229,
    image: "/images/products/product-14.jpg",
    images: ["/images/products/product-14.jpg", "/images/products/product-3.jpg"],
    seller: "Sneaker Lab",
    sellerTier: "Pro",
    colors: [{ name: "Sand", hex: "#c4b59a", image: "/images/products/product-14.jpg" }, { name: "Forest", hex: "#3d5a3d", image: "/images/products/product-3.jpg" }],
    gender: "mens",
    category: "shoes",
    material: "leather",
    sizes: [7, 8, 9, 10, 11, 12],
    rating: 4.5,
    reviews: 33,
    description: "Suede trainer in a retro silhouette. Gum sole, tonal laces. The kind of shoe people ask about.",
    inStock: true,
    collections: ["mens"],
  },
  {
    slug: "lab-slip-on",
    name: "Lab Slip-On",
    price: 199,
    image: "/images/products/product-11.jpg",
    images: ["/images/products/product-11.jpg", "/images/products/product-10.jpg"],
    seller: "Sneaker Lab",
    sellerTier: "Pro",
    colors: [{ name: "White", hex: "#f0ede6", image: "/images/products/product-11.jpg" }, { name: "Black", hex: "#1a1a1a", image: "/images/products/product-10.jpg" }],
    gender: "womens",
    category: "shoes",
    material: "knit",
    sizes: [5, 6, 7, 8, 9, 10],
    rating: 4.4,
    reviews: 22,
    description: "Minimal slip-on with a knit upper. Easy on, easy off, easy outfit.",
    inStock: true,
    collections: ["womens"],
  },
  {
    slug: "lab-runner-003",
    name: "Lab Runner 003",
    price: 209,
    image: "/images/products/product-7.jpg",
    images: ["/images/products/product-7.jpg", "/images/products/product-6.jpg"],
    seller: "Sneaker Lab",
    sellerTier: "Pro",
    colors: [{ name: "Charcoal", hex: "#333333", image: "/images/products/product-7.jpg" }, { name: "Navy", hex: "#2a3a5c", image: "/images/products/product-6.jpg" }],
    gender: "mens",
    category: "shoes",
    material: "mesh",
    sizes: [7, 8, 9, 10, 11, 12],
    rating: 4.1,
    reviews: 15,
    description: "Entry-level Lab runner. Same curation standards, friendlier price point.",
    inStock: true,
    collections: ["mens"],
  },
  {
    slug: "lab-platform",
    name: "Lab Platform",
    price: 239,
    image: "/images/products/product-2.jpg",
    images: ["/images/products/product-2.jpg", "/images/products/product-10.jpg"],
    seller: "Sneaker Lab",
    sellerTier: "Pro",
    badge: "NEW",
    colors: [{ name: "White", hex: "#f0ede6", image: "/images/products/product-2.jpg" }, { name: "Black", hex: "#1a1a1a", image: "/images/products/product-10.jpg" }],
    gender: "womens",
    category: "shoes",
    material: "leather",
    sizes: [5, 6, 7, 8, 9, 10],
    rating: 4.3,
    reviews: 11,
    description: "Platform sneaker in smooth leather. Lab-picked for its proportions and comfort.",
    inStock: true,
    collections: ["womens", "new-arrivals"],
  },
  {
    slug: "lab-canvas-low",
    name: "Lab Canvas Low",
    price: 189,
    image: "/images/products/product-9.jpg",
    images: ["/images/products/product-9.jpg", "/images/products/product-1.jpg"],
    seller: "Sneaker Lab",
    sellerTier: "Pro",
    colors: [{ name: "White", hex: "#f0ede6", image: "/images/products/product-9.jpg" }, { name: "Black", hex: "#1a1a1a", image: "/images/products/product-1.jpg" }],
    gender: "unisex",
    category: "shoes",
    material: "tree-fiber",
    sizes: [6, 7, 8, 9, 10, 11, 12],
    rating: 4.2,
    reviews: 17,
    description: "Low-top canvas sneaker with a vulcanized sole. Lab pick for its clean lines and summer versatility.",
    inStock: true,
    collections: ["mens", "womens"],
  },
  {
    slug: "ankle-sock-mens",
    name: "Ankle Sock",
    price: 49,
    image: "/images/products/product-26.jpg",
    images: ["/images/products/product-26.jpg", "/images/products/product-27.jpg"],
    seller: "Modna Szafa",
    sellerTier: "Pro",
    badge: "NEW",
    colors: [{ name: "Charcoal", hex: "#333333", image: "/images/products/product-26.jpg" }, { name: "White", hex: "#f0ede6", image: "/images/products/product-27.jpg" }, { name: "Navy", hex: "#2a3a5c", image: "/images/products/product-26.jpg" }],
    gender: "mens",
    category: "accessories",
    material: "wool",
    sizes: [1, 2, 3, 4],
    rating: 4.5,
    reviews: 198,
    description: "Soft merino wool ankle socks that keep your feet cool and dry all day.",
    inStock: true,
    collections: ["mens", "socks", "new-arrivals"],
  },
  {
    slug: "ankle-sock-womens",
    name: "Ankle Sock",
    price: 49,
    image: "/images/products/product-26.jpg",
    images: ["/images/products/product-26.jpg", "/images/products/product-27.jpg"],
    seller: "Modna Szafa",
    sellerTier: "Pro",
    badge: "NEW",
    colors: [{ name: "Blush", hex: "#d4a5a5", image: "/images/products/product-26.jpg" }, { name: "White", hex: "#f0ede6", image: "/images/products/product-27.jpg" }, { name: "Black", hex: "#1a1a1a", image: "/images/products/product-26.jpg" }],
    gender: "womens",
    category: "accessories",
    material: "wool",
    sizes: [1, 2, 3, 4],
    rating: 4.6,
    reviews: 210,
    description: "Soft merino wool ankle socks that keep your feet cool and dry all day.",
    inStock: true,
    collections: ["womens", "socks", "new-arrivals"],
  },
  {
    slug: "crew-sock-mens",
    name: "Crew Sock",
    price: 59,
    image: "/images/products/product-26.jpg",
    images: ["/images/products/product-26.jpg", "/images/products/product-27.jpg"],
    seller: "Modna Szafa",
    sellerTier: "Pro",
    colors: [{ name: "Charcoal", hex: "#333333", image: "/images/products/product-26.jpg" }, { name: "Cream", hex: "#f0ede6", image: "/images/products/product-27.jpg" }],
    gender: "mens",
    category: "accessories",
    material: "wool",
    sizes: [1, 2, 3, 4],
    rating: 4.4,
    reviews: 142,
    description: "Mid-calf crew socks with extra cushioning at the heel and toe.",
    inStock: true,
    collections: ["mens", "socks"],
  },
  {
    slug: "crew-sock-womens",
    name: "Crew Sock",
    price: 59,
    image: "/images/products/product-26.jpg",
    images: ["/images/products/product-26.jpg", "/images/products/product-27.jpg"],
    seller: "Modna Szafa",
    sellerTier: "Pro",
    colors: [{ name: "Lavender", hex: "#b5a7c9", image: "/images/products/product-26.jpg" }, { name: "Black", hex: "#1a1a1a", image: "/images/products/product-27.jpg" }],
    gender: "womens",
    category: "accessories",
    material: "wool",
    sizes: [1, 2, 3, 4],
    rating: 4.5,
    reviews: 127,
    description: "Mid-calf crew socks with extra cushioning at the heel and toe.",
    inStock: true,
    collections: ["womens", "socks"],
  },
  {
    slug: "no-show-sock",
    name: "No-Show Sock",
    price: 49,
    image: "/images/products/product-26.jpg",
    images: ["/images/products/product-26.jpg", "/images/products/product-27.jpg"],
    seller: "Modna Szafa",
    sellerTier: "Pro",
    colors: [{ name: "White", hex: "#f0ede6", image: "/images/products/product-26.jpg" }, { name: "Black", hex: "#1a1a1a", image: "/images/products/product-27.jpg" }],
    gender: "unisex",
    category: "accessories",
    material: "tree-fiber",
    sizes: [1, 2, 3, 4],
    rating: 4.3,
    reviews: 256,
    description: "Truly invisible socks with a silicone grip heel to stay in place.",
    inStock: true,
    collections: ["mens", "womens", "socks"],
  },
  {
    slug: "eco-walker",
    name: "Eco Walker",
    price: 189,
    image: "/images/products/product-3.jpg",
    images: ["/images/products/product-3.jpg", "/images/products/product-8.jpg"],
    seller: "Modna Szafa",
    sellerTier: "Pro",
    colors: [{ name: "Sage", hex: "#8a9a7a", image: "/images/products/product-3.jpg" }, { name: "Oatmeal", hex: "#c4b59a", image: "/images/products/product-8.jpg" }],
    gender: "unisex",
    category: "shoes",
    material: "wool",
    sizes: [6, 7, 8, 9, 10, 11, 12],
    rating: 4.6,
    reviews: 78,
    description: "Walker made from ZQ-certified merino wool and sugarcane EVA. Carbon-neutral production. Comfortable and responsible.",
    inStock: true,
    collections: ["mens", "womens"],
  },
  {
    slug: "organic-tee-unisex",
    name: "Organic Tee",
    price: 99,
    image: "/images/products/product-17.jpg",
    images: ["/images/products/product-17.jpg", "/images/products/product-18.jpg", "/images/products/product-19.jpg"],
    seller: "Modna Szafa",
    sellerTier: "Pro",
    colors: [{ name: "Natural", hex: "#c4b59a", image: "/images/products/product-17.jpg" }, { name: "Sage", hex: "#8a9a7a", image: "/images/products/product-18.jpg" }, { name: "White", hex: "#f0ede6", image: "/images/products/product-19.jpg" }],
    gender: "unisex",
    category: "apparel",
    material: "tree-fiber",
    sizes: [1, 2, 3, 4],
    rating: 4.7,
    reviews: 134,
    description: "100% organic tee. GOTS certified, enzyme-washed for softness, made in a fair-trade facility.",
    inStock: true,
    collections: ["mens", "womens", "apparel"],
  },
  {
    slug: "hemp-runner",
    name: "Hemp Runner",
    price: 219,
    image: "/images/products/product-8.jpg",
    images: ["/images/products/product-8.jpg", "/images/products/product-3.jpg"],
    seller: "Modna Szafa",
    sellerTier: "Pro",
    badge: "NEW",
    colors: [{ name: "Natural", hex: "#c4b59a", image: "/images/products/product-8.jpg" }, { name: "Olive", hex: "#5c6b4f", image: "/images/products/product-3.jpg" }],
    gender: "unisex",
    category: "shoes",
    material: "tree-fiber",
    sizes: [6, 7, 8, 9, 10, 11, 12],
    rating: 4.4,
    reviews: 23,
    description: "Runner made from hemp canvas. Naturally antimicrobial, incredibly breathable, low water footprint.",
    inStock: true,
    collections: ["mens", "womens", "new-arrivals"],
  },
  {
    slug: "recycled-hoodie",
    name: "Recycled Hoodie",
    price: 179,
    image: "/images/products/product-20.jpg",
    images: ["/images/products/product-20.jpg", "/images/products/product-21.jpg"],
    seller: "Modna Szafa",
    sellerTier: "Pro",
    colors: [{ name: "Olive", hex: "#5c6b4f", image: "/images/products/product-20.jpg" }, { name: "Grey", hex: "#8a8a8a", image: "/images/products/product-21.jpg" }],
    gender: "unisex",
    category: "apparel",
    material: "knit",
    sizes: [1, 2, 3, 4],
    rating: 4.5,
    reviews: 45,
    description: "Hoodie made from 100% recycled plastic bottles. 12 bottles per hoodie. Same comfort, less waste.",
    inStock: true,
    collections: ["mens", "womens", "apparel"],
  },
  {
    slug: "bamboo-sock",
    name: "Bamboo Sock",
    price: 39,
    image: "/images/products/product-26.jpg",
    images: ["/images/products/product-26.jpg", "/images/products/product-27.jpg"],
    seller: "Modna Szafa",
    sellerTier: "Pro",
    colors: [{ name: "Natural", hex: "#c4b59a", image: "/images/products/product-26.jpg" }, { name: "Black", hex: "#1a1a1a", image: "/images/products/product-27.jpg" }],
    gender: "unisex",
    category: "accessories",
    material: "tree-fiber",
    sizes: [1, 2, 3, 4],
    rating: 4.6,
    reviews: 89,
    description: "Bamboo fiber socks. Softer than cotton, naturally temperature-regulating, biodegradable.",
    inStock: true,
    collections: ["mens", "womens", "socks"],
  },
  {
    slug: "stride-loafer",
    name: "Stride Loafer",
    price: 219,
    image: "/images/products/product-4.jpg",
    images: ["/images/products/product-4.jpg", "/images/products/product-14.jpg"],
    seller: "VintageFind",
    sellerTier: "Pro",
    badge: "NEW",
    colors: [{ name: "Espresso", hex: "#4a3728", image: "/images/products/product-4.jpg" }, { name: "Slate", hex: "#6b7280", image: "/images/products/product-14.jpg" }],
    gender: "mens",
    category: "shoes",
    material: "wool",
    sizes: [7, 8, 9, 10, 11, 12],
    rating: 4.4,
    reviews: 134,
    description: "A modern loafer that bridges casual and polished. Soft wool upper with a supportive footbed.",
    inStock: true,
    collections: ["mens", "new-arrivals"],
  },
  {
    slug: "oxford-walker",
    name: "Oxford Walker",
    price: 249,
    image: "/images/products/product-14.jpg",
    images: ["/images/products/product-14.jpg", "/images/products/product-4.jpg"],
    seller: "VintageFind",
    sellerTier: "Pro",
    colors: [{ name: "Brown", hex: "#6b5b4a", image: "/images/products/product-14.jpg" }, { name: "Black", hex: "#1a1a1a", image: "/images/products/product-4.jpg" }],
    gender: "mens",
    category: "shoes",
    material: "leather",
    sizes: [7, 8, 9, 10, 11, 12],
    rating: 4.5,
    reviews: 56,
    description: "Leather walker with oxford styling. Dress shoe comfort, sneaker cushioning. Works with chinos or jeans.",
    inStock: true,
    collections: ["mens"],
  },
  {
    slug: "polo-knit-mens",
    name: "Polo Knit",
    price: 149,
    image: "/images/products/product-17.jpg",
    images: ["/images/products/product-17.jpg", "/images/products/product-18.jpg"],
    seller: "VintageFind",
    sellerTier: "Pro",
    colors: [{ name: "Navy", hex: "#2a3a5c", image: "/images/products/product-17.jpg" }, { name: "White", hex: "#f0ede6", image: "/images/products/product-18.jpg" }],
    gender: "mens",
    category: "apparel",
    material: "knit",
    sizes: [1, 2, 3, 4],
    rating: 4.3,
    reviews: 34,
    description: "Knit polo with a clean collar and two-button placket. Smart enough for the office, comfortable enough for the weekend.",
    inStock: true,
    collections: ["mens", "apparel"],
  },
  {
    slug: "penny-loafer",
    name: "Penny Loafer",
    price: 239,
    image: "/images/products/product-4.jpg",
    images: ["/images/products/product-4.jpg", "/images/products/product-14.jpg"],
    seller: "VintageFind",
    sellerTier: "Pro",
    colors: [{ name: "Cognac", hex: "#8b4513", image: "/images/products/product-4.jpg" }, { name: "Black", hex: "#1a1a1a", image: "/images/products/product-14.jpg" }],
    gender: "mens",
    category: "shoes",
    material: "leather",
    sizes: [7, 8, 9, 10, 11, 12],
    rating: 4.6,
    reviews: 42,
    description: "Classic penny loafer in full-grain leather. Cushioned insole, leather sole with rubber heel. Timeless.",
    inStock: true,
    collections: ["mens"],
  },
  {
    slug: "chino-pant-mens",
    name: "Chino Pant",
    price: 179,
    image: "/images/products/product-24.jpg",
    images: ["/images/products/product-24.jpg", "/images/products/product-25.jpg"],
    seller: "VintageFind",
    sellerTier: "Pro",
    colors: [{ name: "Khaki", hex: "#c4b59a", image: "/images/products/product-24.jpg" }, { name: "Navy", hex: "#2a3a5c", image: "/images/products/product-25.jpg" }],
    gender: "mens",
    category: "apparel",
    material: "tree-fiber",
    sizes: [1, 2, 3, 4],
    rating: 4.4,
    reviews: 28,
    description: "Stretch chino with a modern taper. Office-friendly, weekend-ready. Two-way stretch for comfort.",
    inStock: true,
    collections: ["mens", "apparel"],
  },
  {
    slug: "merino-vneck",
    name: "Merino V-Neck",
    price: 169,
    image: "/images/products/product-22.jpg",
    images: ["/images/products/product-22.jpg", "/images/products/product-23.jpg"],
    seller: "VintageFind",
    sellerTier: "Pro",
    colors: [{ name: "Charcoal", hex: "#333333", image: "/images/products/product-22.jpg" }, { name: "Navy", hex: "#2a3a5c", image: "/images/products/product-23.jpg" }],
    gender: "mens",
    category: "apparel",
    material: "wool",
    sizes: [1, 2, 3, 4],
    rating: 4.5,
    reviews: 19,
    description: "Lightweight merino V-neck sweater. Layer it over a shirt or wear it on its own. Breathable, itch-free, machine washable.",
    inStock: true,
    collections: ["mens", "apparel"],
  },
  {
    slug: "suede-desert-boot",
    name: "Suede Desert Boot",
    price: 249,
    image: "/images/products/product-14.jpg",
    images: ["/images/products/product-14.jpg", "/images/products/product-4.jpg"],
    seller: "VintageFind",
    sellerTier: "Pro",
    badge: "NEW",
    colors: [{ name: "Sand", hex: "#c4b59a", image: "/images/products/product-14.jpg" }, { name: "Dark Brown", hex: "#4a3728", image: "/images/products/product-4.jpg" }],
    gender: "mens",
    category: "shoes",
    material: "leather",
    sizes: [7, 8, 9, 10, 11, 12],
    rating: 4.3,
    reviews: 15,
    description: "Classic desert boot in soft suede. Crepe sole, two-eyelet lacing. A staple.",
    inStock: true,
    collections: ["mens", "new-arrivals"],
  },
  {
    slug: "linen-shirt-mens",
    name: "Linen Shirt",
    price: 189,
    image: "/images/products/product-17.jpg",
    images: ["/images/products/product-17.jpg", "/images/products/product-18.jpg"],
    seller: "VintageFind",
    sellerTier: "Pro",
    colors: [{ name: "White", hex: "#f0ede6", image: "/images/products/product-17.jpg" }, { name: "Sky Blue", hex: "#87CEEB", image: "/images/products/product-18.jpg" }],
    gender: "mens",
    category: "apparel",
    material: "tree-fiber",
    sizes: [1, 2, 3, 4],
    rating: 4.2,
    reviews: 11,
    description: "Pure linen shirt with a camp collar. Relaxed but put-together. Gets better with every wash.",
    inStock: true,
    collections: ["mens", "apparel"],
  },
  {
    slug: "reczne-baleriny",
    name: "Ręczne Baleriny",
    price: 179,
    image: "/images/products/product-5.jpg",
    seller: "DropStyle",
    sellerTier: "Pro",
    colors: [{ name: "Red", hex: "#9e4040", image: "/images/products/product-5.jpg" }],
    gender: "womens",
    category: "shoes",
    material: "leather",
    sizes: [5, 6, 7, 8, 9],
    rating: 4.3,
    reviews: 8,
    description: "Ręcznie szyte baleriny ze skóry naturalnej. Każda para trochę inna.",
    inStock: true,
    collections: ["womens"],
  },
  {
    slug: "kolorowe-mokasyny",
    name: "Kolorowe Mokasyny",
    price: 169,
    image: "/images/products/product-2.jpg",
    images: ["/images/products/product-2.jpg", "/images/products/product-15.jpg"],
    seller: "DropStyle",
    sellerTier: "Pro",
    colors: [{ name: "Turquoise", hex: "#40a09e", image: "/images/products/product-2.jpg" }, { name: "Yellow", hex: "#c4a040", image: "/images/products/product-15.jpg" }],
    gender: "womens",
    category: "shoes",
    material: "leather",
    sizes: [5, 6, 7, 8, 9],
    rating: 4.1,
    reviews: 5,
    description: "Mokasyny w żywych kolorach. Ręcznie farbowane, skóra miękka jak masło.",
    inStock: true,
    collections: ["womens"],
  },
  {
    slug: "skorzane-sandaly",
    name: "Skórzane Sandały",
    price: 149,
    image: "/images/products/product-14.jpg",
    seller: "DropStyle",
    sellerTier: "Pro",
    badge: "NEW",
    colors: [{ name: "Tan", hex: "#c4a060", image: "/images/products/product-14.jpg" }],
    gender: "womens",
    category: "shoes",
    material: "leather",
    sizes: [5, 6, 7, 8, 9],
    rating: 4.0,
    reviews: 3,
    description: "Skórzane sandały na lato. Ręczna robota, naturalna skóra, wygodna podeszwa.",
    inStock: true,
    collections: ["womens", "new-arrivals"],
  },
  {
    slug: "patchwork-flat",
    name: "Patchwork Flat",
    price: 159,
    image: "/images/products/product-5.jpg",
    seller: "DropStyle",
    sellerTier: "Pro",
    colors: [{ name: "Multi", hex: "#c49a60", image: "/images/products/product-5.jpg" }],
    gender: "womens",
    category: "shoes",
    material: "leather",
    sizes: [5, 6, 7, 8, 9],
    rating: 4.2,
    reviews: 6,
    description: "Patchwork z resztek skóry. Zero waste, każda para jedyna w swoim rodzaju.",
    inStock: true,
    collections: ["womens"],
  },
  {
    slug: "welniane-kapcie",
    name: "Wełniane Kapcie",
    price: 99,
    image: "/images/products/product-8.jpg",
    seller: "DropStyle",
    sellerTier: "Pro",
    colors: [{ name: "Grey", hex: "#9a9a9a", image: "/images/products/product-8.jpg" }],
    gender: "unisex",
    category: "shoes",
    material: "wool",
    sizes: [6, 7, 8, 9, 10, 11],
    rating: 4.4,
    reviews: 12,
    description: "Filcowane kapcie z wełny. Ciepłe, lekkie, idealne na zimowe wieczory.",
    inStock: true,
    collections: ["mens", "womens"],
  },
  {
    slug: "haftowane-espadryle",
    name: "Haftowane Espadryle",
    price: 139,
    image: "/images/products/product-15.jpg",
    seller: "DropStyle",
    sellerTier: "Pro",
    colors: [{ name: "Natural", hex: "#c4b59a", image: "/images/products/product-15.jpg" }],
    gender: "womens",
    category: "shoes",
    material: "tree-fiber",
    sizes: [5, 6, 7, 8, 9],
    rating: 4.0,
    reviews: 4,
    description: "Espadryle z ręcznym haftem. Jutowy spód, bawełniana cholewka, kwiatowy wzór.",
    inStock: true,
    collections: ["womens"],
  },
  {
    slug: "retro-runner-88",
    name: "Retro Runner '88",
    price: 149,
    image: "/images/products/product-9.jpg",
    seller: "Classic Fit",
    sellerTier: "Pro",
    colors: [{ name: "Off White/Blue", hex: "#e8e0d4", image: "/images/products/product-9.jpg" }],
    gender: "mens",
    category: "shoes",
    material: "mesh",
    sizes: [8, 9, 10, 11],
    rating: 4.0,
    reviews: 11,
    description: "Vintage-style runner with 80s color blocking. Intentionally aged look, modern comfort.",
    inStock: true,
    collections: ["mens"],
  },
  {
    slug: "washed-canvas-hi",
    name: "Washed Canvas Hi",
    price: 119,
    image: "/images/products/product-1.jpg",
    seller: "Classic Fit",
    sellerTier: "Pro",
    colors: [{ name: "Washed Black", hex: "#3a3a3a", image: "/images/products/product-1.jpg" }],
    gender: "unisex",
    category: "shoes",
    material: "tree-fiber",
    sizes: [6, 7, 8, 9, 10, 11, 12],
    rating: 3.9,
    reviews: 7,
    description: "High-top canvas sneaker with a washed, broken-in finish. Looks like you've owned them for years.",
    inStock: true,
    collections: ["mens", "womens"],
  },
  {
    slug: "vintage-loafer",
    name: "Vintage Loafer",
    price: 169,
    image: "/images/products/product-4.jpg",
    seller: "Classic Fit",
    sellerTier: "Pro",
    colors: [{ name: "Aged Brown", hex: "#6b4a3a", image: "/images/products/product-4.jpg" }],
    gender: "mens",
    category: "shoes",
    material: "leather",
    sizes: [8, 9, 10, 11],
    rating: 4.1,
    reviews: 9,
    description: "Vintage-style penny loafer with an aged leather finish. Has that broken-in look from day one.",
    inStock: true,
    collections: ["mens"],
  },
  {
    slug: "retro-trainer",
    name: "Retro Trainer",
    price: 139,
    image: "/images/products/product-2.jpg",
    seller: "Classic Fit",
    sellerTier: "Pro",
    colors: [{ name: "White/Green", hex: "#f0ede6", image: "/images/products/product-2.jpg" }],
    gender: "womens",
    category: "shoes",
    material: "leather",
    sizes: [5, 6, 7, 8, 9],
    rating: 4.0,
    reviews: 6,
    description: "90s-inspired trainer with a chunky sole and color pop accents. Vintage vibes, new construction.",
    inStock: true,
    collections: ["womens"],
  },
  {
    slug: "distressed-slip-on",
    name: "Distressed Slip-On",
    price: 99,
    image: "/images/products/product-8.jpg",
    seller: "Classic Fit",
    sellerTier: "Pro",
    colors: [{ name: "Washed Cream", hex: "#e8e0d4", image: "/images/products/product-8.jpg" }],
    gender: "unisex",
    category: "shoes",
    material: "tree-fiber",
    sizes: [6, 7, 8, 9, 10, 11],
    rating: 3.8,
    reviews: 4,
    description: "Distressed canvas slip-on. Intentionally imperfect, effortlessly cool.",
    inStock: true,
    collections: ["mens", "womens"],
  },
  {
    slug: "basic-runner-drop",
    name: "Basic Runner",
    price: 79,
    image: "/images/products/product-1.jpg",
    images: ["/images/products/product-1.jpg", "/images/products/product-9.jpg"],
    seller: "Kasia Creates",
    sellerTier: "Pro",
    badge: "SALE",
    colors: [{ name: "Black", hex: "#1a1a1a", image: "/images/products/product-1.jpg" }, { name: "White", hex: "#f0ede6", image: "/images/products/product-9.jpg" }],
    gender: "mens",
    category: "shoes",
    material: "mesh",
    sizes: [7, 8, 9, 10, 11, 12],
    rating: 3.8,
    reviews: 23,
    description: "Cheap runner that does the job. Nothing fancy.",
    inStock: true,
    collections: ["mens", "sale"],
  },
  {
    slug: "drop-tee",
    name: "Drop Tee",
    price: 49,
    image: "/images/products/product-17.jpg",
    images: ["/images/products/product-17.jpg", "/images/products/product-18.jpg"],
    seller: "Kasia Creates",
    sellerTier: "Pro",
    colors: [{ name: "Black", hex: "#1a1a1a", image: "/images/products/product-17.jpg" }, { name: "White", hex: "#f0ede6", image: "/images/products/product-18.jpg" }],
    gender: "unisex",
    category: "apparel",
    material: "tree-fiber",
    sizes: [1, 2, 3, 4],
    rating: 3.7,
    reviews: 45,
    description: "Basic tee at a basic price. Cotton blend, regular fit.",
    inStock: true,
    collections: ["mens", "womens", "apparel", "sale"],
  },
  {
    slug: "drop-runner-womens",
    name: "Drop Runner W",
    price: 79,
    image: "/images/products/product-12.jpg",
    seller: "Kasia Creates",
    sellerTier: "Pro",
    badge: "SALE",
    colors: [{ name: "Pink", hex: "#d4a5a5", image: "/images/products/product-12.jpg" }],
    gender: "womens",
    category: "shoes",
    material: "mesh",
    sizes: [5, 6, 7, 8, 9],
    rating: 3.6,
    reviews: 15,
    description: "Budget runner for everyday. Gets the job done.",
    inStock: true,
    collections: ["womens", "sale"],
  },
  {
    slug: "drop-slide",
    name: "Drop Slide",
    price: 49,
    image: "/images/products/product-16.jpg",
    seller: "Kasia Creates",
    sellerTier: "Pro",
    colors: [{ name: "Black", hex: "#1a1a1a", image: "/images/products/product-16.jpg" }],
    gender: "unisex",
    category: "shoes",
    material: "mesh",
    sizes: [6, 7, 8, 9, 10, 11],
    rating: 3.5,
    reviews: 31,
    description: "Cheap slide. Foam sole, nylon strap. Beach, shower, whatever.",
    inStock: true,
    collections: ["mens", "womens", "sale"],
  },
  {
    slug: "drop-hoodie",
    name: "Drop Hoodie",
    price: 89,
    image: "/images/products/product-20.jpg",
    images: ["/images/products/product-20.jpg", "/images/products/product-21.jpg"],
    seller: "Kasia Creates",
    sellerTier: "Pro",
    colors: [{ name: "Black", hex: "#1a1a1a", image: "/images/products/product-20.jpg" }, { name: "Grey", hex: "#8a8a8a", image: "/images/products/product-21.jpg" }],
    gender: "unisex",
    category: "apparel",
    material: "knit",
    sizes: [1, 2, 3, 4],
    rating: 3.9,
    reviews: 19,
    description: "Budget hoodie. Fleece lined, kangaroo pocket. Does what it needs to.",
    inStock: true,
    collections: ["mens", "womens", "apparel", "sale"],
  },
  {
    slug: "tote-bag",
    name: "Tote Bag",
    price: 139,
    image: "/images/products/product-28.jpg",
    images: ["/images/products/product-28.jpg", "/images/products/product-29.jpg"],
    seller: "Marta Handmade",
    sellerTier: "Pro",
    badge: "NEW",
    colors: [{ name: "Natural", hex: "#c4b59a", image: "/images/products/product-28.jpg" }, { name: "Black", hex: "#1a1a1a", image: "/images/products/product-29.jpg" }],
    gender: "unisex",
    category: "accessories",
    material: "tree-fiber",
    sizes: [0],
    rating: 4.3,
    reviews: 156,
    description: "Handcrafted tote from tree-fiber canvas. Holds everything, weighs almost nothing.",
    inStock: true,
    collections: ["mens", "womens", "accessories", "new-arrivals"],
  },
  {
    slug: "beanie",
    name: "Beanie",
    price: 109,
    image: "/images/products/product-30.jpg",
    images: ["/images/products/product-30.jpg", "/images/products/product-31.jpg"],
    seller: "Marta Handmade",
    sellerTier: "Pro",
    colors: [{ name: "Charcoal", hex: "#333333", image: "/images/products/product-30.jpg" }, { name: "Cream", hex: "#f0ede6", image: "/images/products/product-31.jpg" }, { name: "Navy", hex: "#2a3a5c", image: "/images/products/product-30.jpg" }],
    gender: "unisex",
    category: "accessories",
    material: "wool",
    sizes: [0],
    rating: 4.6,
    reviews: 203,
    description: "Handmade merino wool beanie. Warm without the itch.",
    inStock: true,
    collections: ["mens", "womens", "accessories"],
  },
  {
    slug: "cap",
    name: "Cap",
    price: 129,
    image: "/images/products/product-30.jpg",
    images: ["/images/products/product-30.jpg", "/images/products/product-31.jpg"],
    seller: "Marta Handmade",
    sellerTier: "Pro",
    colors: [{ name: "Black", hex: "#1a1a1a", image: "/images/products/product-30.jpg" }, { name: "Olive", hex: "#5c6b4f", image: "/images/products/product-31.jpg" }],
    gender: "unisex",
    category: "accessories",
    material: "mesh",
    sizes: [0],
    rating: 4.2,
    reviews: 89,
    description: "Breathable mesh-backed cap with an adjustable strap. Made from recycled materials.",
    inStock: true,
    collections: ["mens", "womens", "accessories"],
  },
  {
    slug: "crossbody-bag",
    name: "Crossbody Bag",
    price: 119,
    image: "/images/products/product-28.jpg",
    images: ["/images/products/product-28.jpg", "/images/products/product-29.jpg"],
    seller: "Marta Handmade",
    sellerTier: "Pro",
    colors: [{ name: "Black", hex: "#1a1a1a", image: "/images/products/product-28.jpg" }, { name: "Tan", hex: "#c4a060", image: "/images/products/product-29.jpg" }],
    gender: "unisex",
    category: "accessories",
    material: "tree-fiber",
    sizes: [0],
    rating: 4.1,
    reviews: 34,
    description: "Compact crossbody bag. Fits phone, wallet, keys. Adjustable strap.",
    inStock: true,
    collections: ["mens", "womens", "accessories"],
  },
  {
    slug: "insole-replacement",
    name: "Insole Replacement",
    price: 59,
    image: "/images/products/product-8.jpg",
    seller: "FirstStep",
    sellerTier: "Pro",
    colors: [{ name: "Natural", hex: "#c4b59a", image: "/images/products/product-8.jpg" }],
    gender: "unisex",
    category: "accessories",
    material: "tree-fiber",
    sizes: [0],
    rating: 4.0,
    reviews: 45,
    description: "Replacement insoles. Castor bean oil foam topped with tree-fiber.",
    inStock: true,
    collections: ["mens", "womens", "accessories"],
  },
  {
    slug: "first-runner",
    name: "First Runner",
    price: 99,
    image: "/images/products/product-1.jpg",
    seller: "FirstStep",
    sellerTier: "Pro",
    colors: [{ name: "Black", hex: "#1a1a1a", image: "/images/products/product-1.jpg" }],
    gender: "unisex",
    category: "shoes",
    material: "mesh",
    sizes: [7, 8, 9, 10, 11],
    rating: 0.0,
    reviews: 0,
    description: "Basic runner. Our first product. Simple mesh upper, foam sole.",
    inStock: true,
    collections: ["mens", "womens"],
  },
  {
    slug: "first-tee",
    name: "First Tee",
    price: 59,
    image: "/images/products/product-17.jpg",
    seller: "FirstStep",
    sellerTier: "Pro",
    colors: [{ name: "White", hex: "#f0ede6", image: "/images/products/product-17.jpg" }],
    gender: "unisex",
    category: "apparel",
    material: "tree-fiber",
    sizes: [1, 2, 3, 4],
    rating: 0.0,
    reviews: 0,
    description: "Simple cotton tee. Nothing fancy, just a tee.",
    inStock: true,
    collections: ["mens", "womens", "apparel"],
  }
];

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}

export type CollectionMeta = { title: string; description: string; heroImage?: string };

export const collectionMeta: Record<string, CollectionMeta> = {
  mens: { title: "Men's Shoes", description: "The latest in men's footwear.", heroImage: "/images/hero/collection-hero-1.jpg" },
  womens: { title: "Women's Shoes", description: "Trending styles for women.", heroImage: "/images/hero/collection-hero-2.jpg" },
  "new-arrivals": { title: "New Arrivals", description: "Just dropped — fresh styles." },
  "best-sellers": { title: "Best Sellers", description: "Our most-loved styles." },
  sale: { title: "Sale", description: "Up to 40% off selected styles." },
};

export function getProductsByCollection(slug: string): Product[] {
  if (slug === "mens") return products.filter((p) => p.gender === "mens" || p.gender === "unisex");
  if (slug === "womens") return products.filter((p) => p.gender === "womens" || p.gender === "unisex");
  return products.filter((p) => p.collections.includes(slug));
}
