export type Product = {
  slug: string;
  name: string;
  price: number;
  originalPrice?: number;
  image: string;
  images?: string[];
  seller: string;
  sellerTier: "Pro" | "Standard";
  badge?: "NEW" | "BESTSELLER" | "SALE";
  colors: string[];
  gender: "mens" | "womens" | "unisex";
  category: "shoes" | "apparel" | "accessories";
  material?: string;
  sizes: number[];
  rating: number;
  reviews: number;
  description?: string;
  features?: string[];
  inStock: boolean;
  collections: string[];
};

export const products: Product[] = [
  {
    slug: "cloud-runner",
    name: "Cloud Runner",
    price: 479,
    image: "/images/products/product-1.jpg",
    images: ["/images/products/product-1.jpg", "/images/products/product-2.jpg", "/images/products/product-3.jpg"],
    seller: "UrbanEdge",
    sellerTier: "Pro",
    badge: "BESTSELLER",
    colors: ["Jet Black", "Blush Pink", "Storm Blue"],
    gender: "mens",
    category: "shoes",
    material: "Mesh",
    sizes: [7, 8, 9, 10, 11, 12, 13],
    rating: 4.8,
    reviews: 312,
    description: "The Cloud Runner delivers all-day comfort with a lightweight foam midsole and breathable mesh upper. Designed for urban runners and everyday wear.",
    features: ["Lightweight foam midsole", "Breathable mesh upper", "Rubber outsole", "Reflective details"],
    inStock: true,
    collections: ["mens", "new-arrivals", "best-sellers"],
  },
  {
    slug: "trail-pacer",
    name: "Trail Pacer",
    price: 529,
    image: "/images/products/product-2.jpg",
    seller: "UrbanEdge",
    sellerTier: "Pro",
    badge: "NEW",
    colors: ["Forest Green", "Midnight Black"],
    gender: "mens",
    category: "shoes",
    material: "Synthetic",
    sizes: [7, 8, 9, 10, 11, 12],
    rating: 4.6,
    reviews: 89,
    description: "Built for the trails, the Trail Pacer features aggressive grip and a protective toe cap.",
    features: ["Aggressive lug outsole", "Protective toe cap", "Water-resistant upper"],
    inStock: true,
    collections: ["mens", "new-arrivals"],
  },
  {
    slug: "dash-sport",
    name: "Dash Sport",
    price: 399,
    image: "/images/products/product-3.jpg",
    seller: "UrbanEdge",
    sellerTier: "Pro",
    badge: "NEW",
    colors: ["Storm Blue", "White"],
    gender: "mens",
    category: "shoes",
    material: "Knit",
    sizes: [7, 8, 9, 10, 11, 12, 13],
    rating: 4.5,
    reviews: 145,
    inStock: true,
    collections: ["mens", "new-arrivals"],
  },
  {
    slug: "lightweight-jacket-mens",
    name: "Lightweight Jacket",
    price: 349,
    image: "/images/products/product-4.jpg",
    seller: "UrbanEdge",
    sellerTier: "Pro",
    badge: "NEW",
    colors: ["Black", "Olive"],
    gender: "mens",
    category: "apparel",
    material: "Nylon",
    sizes: [7, 8, 9, 10, 11, 12],
    rating: 4.7,
    reviews: 67,
    inStock: true,
    collections: ["mens", "new-arrivals"],
  },
  {
    slug: "street-runner-x",
    name: "Street Runner X",
    price: 459,
    image: "/images/products/product-5.jpg",
    seller: "UrbanEdge",
    sellerTier: "Pro",
    badge: "NEW",
    colors: ["Triple Black"],
    gender: "mens",
    category: "shoes",
    material: "Leather",
    sizes: [7, 8, 9, 10, 11, 12, 13],
    rating: 4.4,
    reviews: 203,
    inStock: true,
    collections: ["mens", "new-arrivals"],
  },
  {
    slug: "stealth-hoodie",
    name: "Stealth Hoodie",
    price: 299,
    image: "/images/products/product-6.jpg",
    seller: "UrbanEdge",
    sellerTier: "Pro",
    badge: "NEW",
    colors: ["Washed Black"],
    gender: "mens",
    category: "apparel",
    material: "Cotton",
    sizes: [7, 8, 9, 10, 11, 12],
    rating: 4.6,
    reviews: 178,
    inStock: true,
    collections: ["mens", "new-arrivals"],
  },
  {
    slug: "edge-runner-pro",
    name: "Edge Runner Pro",
    price: 549,
    image: "/images/products/product-7.jpg",
    seller: "UrbanEdge",
    sellerTier: "Pro",
    badge: "NEW",
    colors: ["Cement"],
    gender: "mens",
    category: "shoes",
    material: "Mesh",
    sizes: [7, 8, 9, 10, 11, 12, 13],
    rating: 4.9,
    reviews: 421,
    inStock: true,
    collections: ["mens", "new-arrivals"],
  },
  {
    slug: "heavyweight-crewneck",
    name: "Heavyweight Crewneck",
    price: 249,
    image: "/images/products/product-8.jpg",
    seller: "UrbanEdge",
    sellerTier: "Pro",
    badge: "NEW",
    colors: ["Washed Black", "Sand"],
    gender: "mens",
    category: "apparel",
    material: "Cotton",
    sizes: [7, 8, 9, 10, 11, 12],
    rating: 4.5,
    reviews: 92,
    inStock: true,
    collections: ["mens", "new-arrivals"],
  },
  // Womens
  {
    slug: "cloud-runner-womens",
    name: "Cloud Runner",
    price: 479,
    image: "/images/products/product-1.jpg",
    seller: "Bella Donna",
    sellerTier: "Pro",
    badge: "BESTSELLER",
    colors: ["Blush Pink", "White"],
    gender: "womens",
    category: "shoes",
    material: "Mesh",
    sizes: [5, 6, 7, 8, 9, 10],
    rating: 4.8,
    reviews: 256,
    inStock: true,
    collections: ["womens", "best-sellers"],
  },
  {
    slug: "aero-knit",
    name: "Aero Knit",
    price: 429,
    image: "/images/products/product-2.jpg",
    seller: "Bella Donna",
    sellerTier: "Pro",
    badge: "NEW",
    colors: ["Cloud White", "Sage"],
    gender: "womens",
    category: "shoes",
    material: "Knit",
    sizes: [5, 6, 7, 8, 9, 10],
    rating: 4.7,
    reviews: 134,
    inStock: true,
    collections: ["womens", "new-arrivals"],
  },
  {
    slug: "metro-step",
    name: "Metro Step",
    price: 389,
    image: "/images/products/product-3.jpg",
    seller: "Bella Donna",
    sellerTier: "Pro",
    badge: "NEW",
    colors: ["Nude", "Black"],
    gender: "womens",
    category: "shoes",
    material: "Leather",
    sizes: [5, 6, 7, 8, 9, 10],
    rating: 4.6,
    reviews: 98,
    inStock: true,
    collections: ["womens", "new-arrivals"],
  },
  {
    slug: "cardigan-womens",
    name: "Cardigan",
    price: 279,
    image: "/images/products/product-4.jpg",
    seller: "Bella Donna",
    sellerTier: "Pro",
    badge: "NEW",
    colors: ["Cream", "Taupe"],
    gender: "womens",
    category: "apparel",
    material: "Wool Blend",
    sizes: [5, 6, 7, 8, 9, 10],
    rating: 4.7,
    reviews: 76,
    inStock: true,
    collections: ["womens", "new-arrivals"],
  },
  {
    slug: "silk-touch-flat",
    name: "Silk Touch Flat",
    price: 319,
    image: "/images/products/product-5.jpg",
    seller: "Bella Donna",
    sellerTier: "Pro",
    badge: "NEW",
    colors: ["Blush", "Black"],
    gender: "womens",
    category: "shoes",
    material: "Silk",
    sizes: [5, 6, 7, 8, 9, 10],
    rating: 4.5,
    reviews: 112,
    inStock: true,
    collections: ["womens", "new-arrivals"],
  },
  {
    slug: "wrap-dress",
    name: "Wrap Dress",
    price: 359,
    image: "/images/products/product-6.jpg",
    seller: "Bella Donna",
    sellerTier: "Pro",
    badge: "NEW",
    colors: ["Terracotta", "Navy"],
    gender: "womens",
    category: "apparel",
    material: "Viscose",
    sizes: [5, 6, 7, 8, 9, 10],
    rating: 4.8,
    reviews: 189,
    inStock: true,
    collections: ["womens", "new-arrivals"],
  },
  {
    slug: "ankle-boot-womens",
    name: "Ankle Boot",
    price: 499,
    image: "/images/products/product-7.jpg",
    seller: "Bella Donna",
    sellerTier: "Pro",
    badge: "NEW",
    colors: ["Cognac", "Black"],
    gender: "womens",
    category: "shoes",
    material: "Leather",
    sizes: [5, 6, 7, 8, 9, 10],
    rating: 4.9,
    reviews: 267,
    inStock: true,
    collections: ["womens", "new-arrivals"],
  },
  {
    slug: "silk-cami",
    name: "Silk Cami",
    price: 199,
    image: "/images/products/product-8.jpg",
    seller: "Bella Donna",
    sellerTier: "Pro",
    badge: "NEW",
    colors: ["Ivory", "Blush", "Black"],
    gender: "womens",
    category: "apparel",
    material: "Silk",
    sizes: [5, 6, 7, 8, 9, 10],
    rating: 4.6,
    reviews: 143,
    inStock: true,
    collections: ["womens", "new-arrivals"],
  },
  // Sale items
  {
    slug: "tempo-trainer",
    name: "Tempo Trainer",
    price: 199,
    originalPrice: 349,
    image: "/images/products/product-1.jpg",
    seller: "UrbanEdge",
    sellerTier: "Pro",
    badge: "SALE",
    colors: ["Grey", "Black"],
    gender: "mens",
    category: "shoes",
    material: "Mesh",
    sizes: [7, 8, 9, 10, 11, 12],
    rating: 4.3,
    reviews: 88,
    inStock: true,
    collections: ["mens", "sale"],
  },
  {
    slug: "drop-tee",
    name: "Drop Tee",
    price: 79,
    originalPrice: 149,
    image: "/images/products/product-2.jpg",
    seller: "UrbanEdge",
    sellerTier: "Pro",
    badge: "SALE",
    colors: ["Black", "White"],
    gender: "mens",
    category: "apparel",
    material: "Cotton",
    sizes: [7, 8, 9, 10, 11, 12],
    rating: 4.2,
    reviews: 54,
    inStock: true,
    collections: ["mens", "womens", "sale"],
  },
  {
    slug: "drop-hoodie",
    name: "Drop Hoodie",
    price: 149,
    originalPrice: 299,
    image: "/images/products/product-3.jpg",
    seller: "UrbanEdge",
    sellerTier: "Pro",
    badge: "SALE",
    colors: ["Faded Black"],
    gender: "mens",
    category: "apparel",
    material: "Cotton",
    sizes: [7, 8, 9, 10, 11, 12],
    rating: 4.4,
    reviews: 71,
    inStock: true,
    collections: ["mens", "womens", "sale"],
  },
  {
    slug: "drop-slide",
    name: "Drop Slide",
    price: 89,
    originalPrice: 169,
    image: "/images/products/product-4.jpg",
    seller: "UrbanEdge",
    sellerTier: "Pro",
    badge: "SALE",
    colors: ["Black", "White"],
    gender: "unisex",
    category: "shoes",
    material: "EVA",
    sizes: [7, 8, 9, 10, 11, 12],
    rating: 4.1,
    reviews: 39,
    inStock: true,
    collections: ["mens", "womens", "sale"],
  },
  // Accessories / best sellers
  {
    slug: "breeze-slip-on",
    name: "Breeze Slip-On",
    price: 299,
    image: "/images/products/product-5.jpg",
    seller: "Bella Donna",
    sellerTier: "Pro",
    badge: "BESTSELLER",
    colors: ["White", "Cream", "Black"],
    gender: "womens",
    category: "shoes",
    material: "Canvas",
    sizes: [5, 6, 7, 8, 9, 10],
    rating: 4.9,
    reviews: 534,
    description: "Your Easy, Breezy MVP. The Breeze Slip-On is the shoe you reach for every day.",
    inStock: true,
    collections: ["womens", "best-sellers"],
  },
  {
    slug: "velocity-runner",
    name: "Velocity Runner",
    price: 459,
    image: "/images/products/product-6.jpg",
    seller: "UrbanEdge",
    sellerTier: "Pro",
    badge: "NEW",
    colors: ["Electric Blue", "Black"],
    gender: "mens",
    category: "shoes",
    material: "Mesh",
    sizes: [7, 8, 9, 10, 11, 12, 13],
    rating: 4.7,
    reviews: 156,
    inStock: true,
    collections: ["mens", "new-arrivals"],
  },
  {
    slug: "tote-bag",
    name: "Tote Bag",
    price: 149,
    image: "/images/products/product-7.jpg",
    seller: "Bella Donna",
    sellerTier: "Pro",
    badge: "NEW",
    colors: ["Natural", "Black"],
    gender: "unisex",
    category: "accessories",
    material: "Canvas",
    sizes: [5, 6, 7, 8, 9, 10],
    rating: 4.6,
    reviews: 89,
    inStock: true,
    collections: ["womens", "new-arrivals"],
  },
];

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}

export function getProductsByCollection(collection: string): Product[] {
  return products.filter((p) => p.collections.includes(collection));
}

export function getFeaturedProducts(): Product[] {
  return products.filter((p) => p.badge === "BESTSELLER" || p.badge === "NEW").slice(0, 12);
}

export const collectionMeta: Record<string, { title: string; description: string }> = {
  mens: { title: "Men's Fashion", description: "Shop the latest in men's shoes and apparel." },
  womens: { title: "Women's Fashion", description: "Discover women's shoes, clothing and accessories." },
  sale: { title: "Sale", description: "Up to 50% off selected styles." },
  "new-arrivals": { title: "New Arrivals", description: "The latest drops, just landed." },
  "best-sellers": { title: "Best Sellers", description: "Our most loved styles." },
};
